### ISSUE TITLE
HTC, workflow engine scalling, Too many open files, pickle, shutil

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida_core#1010]
Launch ~ 1000 calculation and your machine will go: 'IOError: Too many open files'
for each of them.... (only not the last ones...)
Does not occur, if I just run some. Also as far as I remember before the pickles this problem did not occur. 

Full stacktrace:
```
-> ERROR at 2017-12-20 09:09:16.273925+00:00
|   exception occurred:
|   Traceback (most recent call last):
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/daemon.py", line 50, in tick_workflow_engine
|       proc.run_until(ProcessState.DESTROYED)
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/process.py", line 316, in run_until
|       if not self.tick() and break_on_wait_not_ready:
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/process.py", line 283, in tick
|       return self.__director.tick()
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/process.py", line 808, in tick
|       MONITOR.process_failed(self._proc.pid)
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/process_monitor.py", line 69, in process_failed
|       ProcessMonitorListener.on_monitored_process_failed, pid)
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/util.py", line 39, in fire_event
|       getattr(l, event_function.__name__)(*args, **kwargs)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/process.py", line 529, in on_monitored_process_failed
|       aiida.work.util.ProcessStack.pop(pid=pid)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/util.py", line 92, in pop
|       assert pid == cls.pids()[-1], \
|   IndexError: list index out of range
+-> ERROR at 2017-12-20 09:09:53.220394+00:00
|   exception occurred:
|   Traceback (most recent call last):
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/daemon.py", line 45, in tick_workflow_engine
|       proc.tick()
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/process.py", line 283, in tick
|       return self.__director.tick()
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/process.py", line 808, in tick
|       MONITOR.process_failed(self._proc.pid)
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/process_monitor.py", line 69, in process_failed
|       ProcessMonitorListener.on_monitored_process_failed, pid)
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/util.py", line 39, in fire_event
|       getattr(l, event_function.__name__)(*args, **kwargs)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/persistence.py", line 327, in on_monitored_process_failed
|       self._release_process(pid, self.failed_directory)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/persistence.py", line 365, in _release_process
|       shutil.copyfile(pickle_path, to)
|     File "/usr/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
|       with open(src, 'rb') as fsrc:
|   IOError: [Errno 24] Too many open files: u'/Users/broeder/aiida/aiida_run/repository-broeder_work/workflows/running/100000.pickle'
+-> ERROR at 2017-12-20 09:10:12.930844+00:00
|   exception occurred:
|   Traceback (most recent call last):
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/daemon.py", line 45, in tick_workflow_engine
|       proc.tick()
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/process.py", line 283, in tick
|       return self.__director.tick()
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/process.py", line 808, in tick
|       MONITOR.process_failed(self._proc.pid)
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/process_monitor.py", line 69, in process_failed
|       ProcessMonitorListener.on_monitored_process_failed, pid)
|     File "/Users/broeder/aiida/github/envs/env_aiida/lib/python2.7/site-packages/plum/util.py", line 39, in fire_event
|       getattr(l, event_function.__name__)(*args, **kwargs)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/persistence.py", line 327, in on_monitored_process_failed
|       self._release_process(pid, self.failed_directory)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/persistence.py", line 365, in _release_process
|       shutil.copyfile(pickle_path, to)
|     File "/usr/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
|       with open(src, 'rb') as fsrc:
|   IOError: [Errno 24] Too many open files: u'/Users/broeder/aiida/aiida_run/repository-broeder_work/workflows/running/100000.pickle'

```
Anybody ran into this?
Is my environment messed up? Since the shutil package was not used from the env_aiida... I will check on this.

```
broeder@mb-broeder:~ % ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
...
```

for open file limits, there are system wide and shell settings...

**Comment by broeder-j** [comment]
```
launchctl limit maxfiles
sudo launchctl limit maxfiles x unlimited
```

Note: One can increase the limit manually until the kernel limit.
Therefore, this border can be pushed to a couple of thousands.

I suggest to give a recommendation to AiiDA users to do so and think of a way to make sure to not have to m any pickles open at a time.

**Comment by giovannipizzi** [comment]
@muhrin @sphuber

**Comment by muhrin** [comment]
Thanks a lot Jens!

We've moved away from pickles in the up to date workflows but there branch is still a couple of weeks away from being develop mergeable.  Now the instance state is just saved as an attribute in the node (hence no file limit problems).

Keep an eye on this ticket for when we merge.
