### ISSUE TITLE
verdi daemon on paid leave

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1032]
I'm running aiida 0.10.1

Supposedly, the daemon is working just fine
```
$ verdi daemon status
# Most recent daemon timestamp:0h:00m:01s ago
## Found 1 process running:
   * aiida-daemon[aiida-daemon] RUNNING    pid 32416, uptime 0:09:58
```

but for some reason, it started refusing to touch any new calculations.
```
# Last daemon state_updater check: 0h:00m:03s ago (at 21:44:31 on 2018-01-08)
  PK  Creation    State             Sched. state    Computer    Type
----  ----------  ----------------  --------------  ----------  ----------------
...
 407  41m ago     NEW                               localhost   zeopp.network
```

It also refuses to be persuaded to return to sanity via stop/start/restart.

I'm not entirely sure what caused the problem, perhaps a trauma from trying to kill a calculation that could not be killed?
```
$ verdi calculation kill 147
Are you sure to kill 1 calculation? [Y/N] Y
01/08/2018 09:37:34 PM, aiida: [ERROR] Unable to find plugin for type 'calculation.job.raspa.RaspaCalculation.' (node= 147), will use base Node class
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp2/bin/verdi", line 11, in <module>
    sys.exit(run())
  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp2/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1043, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp2/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1028, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp2/lib/python2.7/site-packages/aiida/cmdline/baseclass.py", line 190, in run
    function_to_call(*args[1:])
  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp2/lib/python2.7/site-packages/aiida/cmdline/commands/calculation.py", line 659, in calculation_kill
    c.kill()  # Calc.kill(calc_pk)
AttributeError: 'Node' object has no attribute 'kill'
```

`verdi daemon logshow` now reads like this:
```
[2018-01-08 21:45:58,128: INFO/MainProcess] Received task: tasks.submitter[8890dde5-5b47-4628-9bf6-683e5c2f157b]
[2018-01-08 21:45:58,130: WARNING/Worker-3] aiida.daemon.tasks.submitter:  Checking for calculations to submit
01/08/2018 09:45:58 PM, aiida: [ERROR] Unable to find plugin for type 'calculation.job.raspa.RaspaCalculation.' (node= 147), will use base Node class
01/08/2018 09:45:58 PM, aiida.execmanager: [WARNING] There was an exception for calculation 147 (AttributeError): 'Node' object has no attribute 'get_state'
[2018-01-08 21:45:58,178: INFO/MainProcess] Task tasks.submitter[8890dde5-5b47-4628-9bf6-683e5c2f157b] succeeded in 0.0485491380095s: None
[2018-01-08 21:46:00,976: INFO/Beat] Scheduler: Sending due task tasks.workflow_stepper (tasks.workflow_stepper)
[2018-01-08 21:46:00,987: INFO/Beat] Scheduler: Sending due task tasks.updater (tasks.updater)
[2018-01-08 21:46:01,044: INFO/Beat] Scheduler: Sending due task tasks.submitter (tasks.submitter)
[2018-01-08 21:46:01,175: INFO/MainProcess] Received task: tasks.workflow_stepper[bbcb4e71-b3f1-40cc-ac30-44d1b087d345]
[2018-01-08 21:46:01,177: WARNING/Worker-9] aiida.daemon.tasks.workflowmanager:  Checking for workflows to manage
[2018-01-08 21:46:01,186: INFO/MainProcess] Received task: tasks.submitter[5bac9321-1aaf-450a-8aca-6c706fae693b]
[2018-01-08 21:46:01,187: WARNING/Worker-2] aiida.daemon.tasks.submitter:  Checking for calculations to submit
[2018-01-08 21:46:01,189: WARNING/Worker-9] aiida.daemon.tasks.workflowmanager: running execute_steps
[2018-01-08 21:46:01,194: INFO/MainProcess] Task tasks.workflow_stepper[bbcb4e71-b3f1-40cc-ac30-44d1b087d345] succeeded in 0.0174590509851s: None
01/08/2018 09:46:01 PM, aiida: [ERROR] Unable to find plugin for type 'calculation.job.raspa.RaspaCalculation.' (node= 147), will use base Node class
01/08/2018 09:46:01 PM, aiida.execmanager: [WARNING] There was an exception for calculation 147 (AttributeError): 'Node' object has no attribute 'get_state'
[2018-01-08 21:46:01,239: INFO/MainProcess] Task tasks.submitter[5bac9321-1aaf-450a-8aca-6c706fae693b] succeeded in 0.0523021009285s: None
[2018-01-08 21:46:01,334: INFO/Beat] Scheduler: Sending due task tasks.tick_work (tasks.tick_work)
[2018-01-08 21:46:01,340: INFO/Beat] Scheduler: Sending due task tasks.retriever (tasks.retriever)
[2018-01-08 21:46:02,205: INFO/MainProcess] Received task: tasks.retriever[caa97b1b-e23b-4600-b09f-1341708afe67]
[2018-01-08 21:46:02,207: WARNING/Worker-5] aiida.daemon.tasks.retrieve:  Checking for calculations to retrieve
[2018-01-08 21:46:02,236: INFO/MainProcess] Task tasks.retriever[caa97b1b-e23b-4600-b09f-1341708afe67] succeeded in 0.0292767030187s: None
```

How does one get the daemon back on track?

P.S. Btw, I would have just deleted the rogue calculation but the node deletion scripts only work with the django backend. It's high time that we implement it for both backends and make `verdi node delete` part of the user interface #923

**Comment by broeder-j** [comment]
Had the same problem, recently. No idea why it happened. But after I manually killed ALL python processes for the daemon. I could start the daemon again it it was sane again.

**Comment by sphuber** [comment]
The problem is here:

```
01/08/2018 09:46:01 PM, aiida: [ERROR] Unable to find plugin for type 'calculation.job.raspa.RaspaCalculation.' (node= 147), will use base Node class
```

The daemon does find the calculation in the `NEW` state, tries to load it and move it to `TOSUBMIT` state. However, since the calculation class cannot be found by the pluginloader, the base class is used which does not have all the necessary attributes, thereby failing the daemons attempt to submit the calculation.

Normally the solution is to call `reentry scan` to make sure that the calculation is registered with `reentry` and the cache is updated and restart the daemon (check also `verdi calculation plugins`). Why the daemon won't restart is another problem. Maybe try to kill the process manually

**Comment by ltalirz** [comment]
@broeder-j Thanks for the input!
This problem seems to be different from the one you experienced: when I do `verdi daemon stop`, all celery processes are gone and the .pid and .sock files in .aiida/daemon are deleted.

@sphuber I forgot to clarify: The error message concerning the plugin refers to an old calculation. The `NEW` calculation is using a plugin that is installed and working
I now restarted the Macbook, and now I receive an error message already when starting the daemon:
```
Clearing all locks ...
Starting AiiDA Daemon ...
Daemon started
LOG:  unexpected EOF on client connection with an open transaction
```
I guess, I'll try to redo `verdi quicksetup` as you suggested

**Comment by sphuber** [comment]
`verdi setup` don't do the quick version

**Comment by ltalirz** [comment]
The problem with `NEW` calculations was my mistake - I was no longer properly submitting calculations, sorry about that.
In a new conda environment, with a clean profile, things are now working fine again, also with aiida 0.10.1
