### ISSUE TITLE
Calculation ends in RETRIEVALFAILED due to peculiar paramiko failure

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#1106]
For a few calculations on a specific university cluster, the retrieval never works. The error message given by Paramiko is below, and is not very helpful. A few comments:
- It is just a very few calculations for a specific  cluster. In general, retrieval works fine on that cluster for most calculations.
- This calculations always fail retrieving, i.e. setting the state back manually and trying to retrieve again, fails with the same message for these calculations.
- There is nothing wrong with the calculations, all files to retrieve exist and are readable. The files are not exceptionally larger, either.

Has this ever occurred before? I've upgraded paramiko as well, to no avail.

```02/05/2018 09:10:26 AM, aiida.execmanager: [ERROR] Error retrieving calc 2088674. Traceback: Traceback (most recent call last):
  File "/home/kahle/git/AiiDA/aiida_core-screening/aiida/daemon/execmanager.py", line 726, in retrieve_computed_for_authinfo
    retrieve_files_from_list(calc, t, folder, retrieve_list)
  File "/home/kahle/git/AiiDA/aiida_core-screening/aiida/daemon/execmanager.py", line 900, in retrieve_files_from_list
    transport.get(rem, os.path.join(folder.abspath, loc), ignore_nonexisting=True)
  File "/home/kahle/git/AiiDA/aiida_core-screening/aiida/transport/plugins/ssh.py", line 976, in get
    self.getfile( remotepath,localpath,callback,dereference,overwrite )
  File "/home/kahle/git/AiiDA/aiida_core-screening/aiida/transport/plugins/ssh.py", line 1009, in getfile
    return self.sftp.get(remotepath,localpath,callback)
  File "/home/kahle/.virtualenvs/screening/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 770, in get
    size = self.getfo(remotepath, fl, callback)
  File "/home/kahle/.virtualenvs/screening/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 750, in getfo
    reader=fr, writer=fl, file_size=file_size, callback=callback
  File "/home/kahle/.virtualenvs/screening/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 647, in _transfer_with_callback
    data = reader.read(32768)
  File "/home/kahle/.virtualenvs/screening/local/lib/python2.7/site-packages/paramiko/file.py", line 212, in read
    new_data = self._read(read_size)
  File "/home/kahle/.virtualenvs/screening/local/lib/python2.7/site-packages/paramiko/sftp_file.py", line 173, in _read
    data = self._read_prefetch(size)
  File "/home/kahle/.virtualenvs/screening/local/lib/python2.7/site-packages/paramiko/sftp_file.py", line 154, in _read_prefetch
    self._check_exception()
  File "/home/kahle/.virtualenvs/screening/local/lib/python2.7/site-packages/paramiko/sftp_file.py", line 559, in _check_exception
    raise x
IOError: Failure
```

**Comment by lekah** [comment]
@giovannipizzi  @nmounet  Have you seen this before?

**Comment by lekah** [comment]
On further investigation, I suspect problems with the filesystem on the cluster.

**Comment by giovannipizzi** [comment]
Indeed I think it might be a cluster problem. I'm closing this for now, if it doesn't reproduce again. If you think this might be dealt with differently, feel free to reopen.
