### ISSUE TITLE
Database integrity errors in tornado futures during testing

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1211]
This happens for both backends, where during some tests, depending on which tests are ran together, database operations are performed on nodes that have already been deleted, resulting in `IntegrityErrors` like the one below:

```
....ERROR:tornado.application:Exception in callback <functools.partial object at 0x7f0331d529f0>
Traceback (most recent call last):
  File "/home/sphuber/.virtualenvs/aiida_workflows/local/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/sphuber/.virtualenvs/aiida_workflows/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/sphuber/code/plum/plumpy/events.py", line 122, in _run
    self._process.callback_excepted(self._callback, exc_info[1], exc_info[2])
  File "/home/sphuber/code/plum/plumpy/base_process.py", line 529, in callback_excepted
    self.fail(exception, trace)
  File "/home/sphuber/code/plum/plumpy/base/state_machine.py", line 73, in transition
    result = wrapped(self, *a, **kw)
  File "/home/sphuber/code/plum/plumpy/base_process.py", line 738, in fail
    self.transition_to(ProcessState.EXCEPTED, exception, trace_back)
  File "/home/sphuber/code/plum/plumpy/processes.py", line 388, in transition_to
    super(Process, self).transition_to(new_state, *args, **kwargs)
  File "/home/sphuber/code/plum/plumpy/base/state_machine.py", line 278, in transition_to
    self.transition_failed(initial_state_label, label, *sys.exc_info()[1:])
  File "/home/sphuber/code/plum/plumpy/base/state_machine.py", line 291, in transition_failed
    raise_(type(exception), exception, trace)
  File "/home/sphuber/code/plum/plumpy/base/state_machine.py", line 268, in transition_to
    call_with_super_check(new_state.enter)
  File "/home/sphuber/code/plum/plumpy/base/utils.py", line 33, in call_with_super_check
    fn(*args, **kwargs)
  File "/home/sphuber/code/plum/plumpy/base/utils.py", line 20, in new_fn
    fn(self, *args, **kwargs)
  File "/home/sphuber/code/plum/plumpy/base/state_machine.py", line 126, in enter
    call_with_super_check(self.state_machine.on_entering, self)
  File "/home/sphuber/code/plum/plumpy/base/utils.py", line 33, in call_with_super_check
    fn(*args, **kwargs)
  File "/home/sphuber/code/aiida/env/workflows/aiida-core/aiida/work/processes.py", line 180, in on_entering
    self.update_node_state(state)
  File "/home/sphuber/code/aiida/env/workflows/aiida-core/aiida/work/processes.py", line 313, in update_node_state
    self.calc._set_process_state(state.LABEL)
  File "/home/sphuber/code/aiida/env/workflows/aiida-core/aiida/orm/implementation/general/calculation/__init__.py", line 198, in _set_process_state
    return self._set_attr(self.PROCESS_STATE_KEY, state)
  File "/home/sphuber/code/aiida/env/workflows/aiida-core/aiida/orm/mixins.py", line 189, in _set_attr
    super(Sealable, self)._set_attr(key, value, stored_check=False, **kwargs)
  File "/home/sphuber/code/aiida/env/workflows/aiida-core/aiida/orm/implementation/general/node.py", line 855, in _set_attr
    self._set_db_attr(key, clean_value(value))
  File "/home/sphuber/code/aiida/env/workflows/aiida-core/aiida/orm/implementation/django/node.py", line 279, in _set_db_attr
    DbAttribute.set_value_for_node(self.dbnode, key, value)
  File "/home/sphuber/code/aiida/env/workflows/aiida-core/aiida/backends/djsite/db/models.py", line 1217, in set_value_for_node
    stop_if_existing=stop_if_existing)
  File "/home/sphuber/code/aiida/env/workflows/aiida-core/aiida/backends/djsite/db/models.py", line 703, in set_value
    cls.objects.bulk_create(to_store)
  File "/home/sphuber/.virtualenvs/aiida_workflows/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sphuber/.virtualenvs/aiida_workflows/local/lib/python2.7/site-packages/django/db/models/query.py", line 409, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/home/sphuber/.virtualenvs/aiida_workflows/local/lib/python2.7/site-packages/django/db/transaction.py", line 339, in __exit__
    connection.commit()
  File "/home/sphuber/.virtualenvs/aiida_workflows/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 176, in commit
    self._commit()
  File "/home/sphuber/.virtualenvs/aiida_workflows/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
  File "/home/sphuber/.virtualenvs/aiida_workflows/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/sphuber/.virtualenvs/aiida_workflows/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
IntegrityError: insert or update on table "db_dbattribute" violates foreign key constraint "db_dbattribute_dbnode_id_783fe2b9b1ee948f_fk_db_dbnode_id"
DETAIL:  Key (dbnode_id)=(95325) is not present in table "db_dbnode".
```

One example can be found by running `verdi -p test_django devel tests db.work.persistence`

**Comment by sphuber** [comment]
Fixed in #1315
