### ISSUE TITLE
RabbitMQ connection automatically closed after time out

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1247]
When the daemon has been running a while and one tries to submit another process to it, the following exception will be raised due to connection be stopped:

```
Traceback (most recent call last):
  File "/home/sphuber/.virtualenvs/aiida_dev/lib/python2.7/site-packages/kiwipy/rmq/tasks.py", line 144, in _on_task
    result = subscriber(task)
  File "/home/sphuber/.virtualenvs/aiida_dev/src/plumpy/plumpy/process_comms.py", line 243, in __call__
    return self._launch(task)
  File "/home/sphuber/code/aiida/env/dev/aiida-core/aiida/work/rmq.py", line 153, in _launch
    return super(ProcessLauncher, self)._launch(task)
  File "/home/sphuber/.virtualenvs/aiida_dev/src/plumpy/plumpy/process_comms.py", line 256, in _launch
    proc = proc_class(*args, **kwargs)
  File "/home/sphuber/.virtualenvs/aiida_dev/src/plumpy/plumpy/base/state_machine.py", line 154, in __call__
    inst.transition_to(inst.create_initial_state())
  File "/home/sphuber/.virtualenvs/aiida_dev/src/plumpy/plumpy/processes.py", line 400, in transition_to
    self.on_entered(initial_state)
  File "/home/sphuber/.virtualenvs/aiida_dev/src/plumpy/plumpy/processes.py", line 347, in on_entered
    subject="state_changed.{}.{}".format(from_label, self.state.value)
  File "/home/sphuber/.virtualenvs/aiida_dev/lib/python2.7/site-packages/kiwipy/rmq/communicator.py", line 304, in broadcast_send
    return self._message_publisher.broadcast_send(body, sender, subject, correlation_id)
  File "/home/sphuber/.virtualenvs/aiida_dev/lib/python2.7/site-packages/kiwipy/rmq/communicator.py", line 48, in broadcast_send
    self.action_message(message)
  File "/home/sphuber/.virtualenvs/aiida_dev/lib/python2.7/site-packages/kiwipy/rmq/messages.py", line 316, in action_message
    message.send(self)
  File "/home/sphuber/.virtualenvs/aiida_dev/lib/python2.7/site-packages/kiwipy/rmq/messages.py", line 111, in send
    publisher.publish_msg(self.message, defaults.BROADCAST_TOPIC)
  File "/home/sphuber/.virtualenvs/aiida_dev/lib/python2.7/site-packages/kiwipy/rmq/messages.py", line 339, in publish_msg
    mandatory=mandatory
  File "/home/sphuber/.virtualenvs/aiida_dev/lib/python2.7/site-packages/kiwipy/rmq/messages.py", line 354, in do_publish
    self._publish_channel.publish(*args, **kwargs)
  File "/home/sphuber/.virtualenvs/aiida_dev/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2127, in publish
    self._flush_output(self._message_confirmation_result.is_ready)
  File "/home/sphuber/.virtualenvs/aiida_dev/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output
    *waiters)
  File "/home/sphuber/.virtualenvs/aiida_dev/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 474, in _flush_output
    result.reason_text)
ConnectionClosed: (-1, "error(104, 'Connection reset by peer')")
```

**Comment by sphuber** [comment]
Fixed in PR #1248
