### ISSUE TITLE
Nested inputs are not stored when submitting.

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1268]
To reproduce: 

In ``workchains.py``:

```
from aiida.orm.data.bool import Bool
from aiida.work.workchain import WorkChain

class TestWorkChain(WorkChain):
    @classmethod
    def define(cls, spec):
        super(TestWorkChain, cls).define(spec)
        spec.input('foo.bar.baz', valid_type=Bool)

        spec.outline(cls.do_test)

    def do_test(self):
        assert self.inputs.foo.bar.baz
```

In the submission script:

```
#!/usr/bin/env runaiida

from aiida.work.launch import submit
from aiida.orm.data.bool import Bool
from workchains import TestWorkChain

submit(TestWorkChain, foo={'bar': {'baz': Bool(True)}})
```

Error (because the input doesn't appear to be stored): 
```
Traceback (most recent call last):
  File "/home/greschd/.virtualenvs/aiida_dev/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/greschd/programming/aiida/aiida_core/aiida/cmdline/verdilib.py", line 1040, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/greschd/programming/aiida/aiida_core/aiida/cmdline/verdilib.py", line 1025, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/greschd/programming/aiida/aiida_core/aiida/cmdline/verdilib.py", line 870, in run
    exec (f, globals_dict)
  File "./submit.py", line 7, in <module>
    node = submit(TestWorkChain, foo={'bar': {'baz': Bool(True)}})
  File "/home/greschd/programming/aiida/aiida_core/aiida/work/launch.py", line 31, in submit
    process_class, init_kwargs={'inputs': inputs})
  File "/home/greschd/programming/aiida/aiida_core/aiida/work/rmq.py", line 232, in execute_process_start
    self._communicator.await(action)
  File "/home/greschd/.virtualenvs/aiida_dev/src/kiwipy/kiwipy/rmq/communicator.py", line 309, in await
    return self._loop.run_sync(lambda: future, timeout=timeout)
  File "/home/greschd/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/home/greschd/.virtualenvs/aiida_dev/src/kiwipy/kiwipy/futures.py", line 43, in result
    return super(Future, self).result(timeout=0.)
  File "/home/greschd/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
kiwipy.communications.RemoteException: No node was found
Traceback (most recent call last):
  File "/home/greschd/.virtualenvs/aiida_dev/src/kiwipy/kiwipy/rmq/tasks.py", line 143, in _on_task
    task = self._decode(body)
  File "/home/greschd/programming/aiida/aiida_core/aiida/work/rmq.py", line 108, in decode_response
    return deserialize_data(response)
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 73, in deserialize_data
    return {decode_key(key): deserialize_data(value) for key, value in data.iteritems()}
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 73, in <dictcomp>
    return {decode_key(key): deserialize_data(value) for key, value in data.iteritems()}
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 73, in deserialize_data
    return {decode_key(key): deserialize_data(value) for key, value in data.iteritems()}
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 73, in <dictcomp>
    return {decode_key(key): deserialize_data(value) for key, value in data.iteritems()}
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 73, in deserialize_data
    return {decode_key(key): deserialize_data(value) for key, value in data.iteritems()}
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 73, in <dictcomp>
    return {decode_key(key): deserialize_data(value) for key, value in data.iteritems()}
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 73, in deserialize_data
    return {decode_key(key): deserialize_data(value) for key, value in data.iteritems()}
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 73, in <dictcomp>
    return {decode_key(key): deserialize_data(value) for key, value in data.iteritems()}
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 73, in deserialize_data
    return {decode_key(key): deserialize_data(value) for key, value in data.iteritems()}
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 73, in <dictcomp>
    return {decode_key(key): deserialize_data(value) for key, value in data.iteritems()}
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/serialize.py", line 77, in deserialize_data
    return load_node(uuid=data[len(_PREFIX_VALUE_NODE):])
  File "/home/greschd/programming/aiida/aiida_core/aiida/orm/utils.py", line 213, in load_node
    raise NotExistent('No node was found')
NotExistent: No node was found


```

**Comment by sphuber** [comment]
Fixed in #1269
