### ISSUE TITLE
verdi work status fails when the workchain calls an InlineCalculation

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1273]
Trying to run ``verdi work status`` with a workchain that calls an InlineCalculation gives the following error:

```
Traceback (most recent call last):
  File "/home/greschd/.virtualenvs/aiida_dev/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/greschd/programming/aiida/aiida_core/aiida/cmdline/verdilib.py", line 1040, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/greschd/programming/aiida/aiida_core/aiida/cmdline/verdilib.py", line 1025, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/greschd/programming/aiida/aiida_core/aiida/cmdline/baseclass.py", line 221, in run
    function_to_call(*args[1:])
  File "/home/greschd/programming/aiida/aiida_core/aiida/cmdline/commands/work.py", line 52, in cli
    verdi()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/greschd/programming/aiida/aiida_core/aiida/cmdline/commands/work.py", line 416, in status
    print_call_graph(calc_node)
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/ascii_vis.py", line 193, in print_call_graph
    call_tree = build_call_graph(calc_node, info_fn=info_fn)
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/ascii_vis.py", line 202, in build_call_graph
    return info_string, [build_call_graph(child, info_fn) for child in called]
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/ascii_vis.py", line 202, in build_call_graph
    return info_string, [build_call_graph(child, info_fn) for child in called]
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/ascii_vis.py", line 198, in build_call_graph
    info_string = info_fn(calc_node)
  File "/home/greschd/programming/aiida/aiida_core/aiida/utils/ascii_vis.py", line 181, in calc_info
    raise TypeError('Unknown type: {}'.format(type(calc_node)))
TypeError: Unknown type: <class 'aiida.orm.implementation.general.calculation.inline.InlineCalculation'>
```

**Comment by sphuber** [comment]
Fixed in #1276
