### ISSUE TITLE
IcsdDbImporter uses wrong attribute to store the results

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1287]
The base class expects the query results to be stored in `self._results` however the `IcsdDbImporter` uses `self.results` instead, resulting in the following exception:

```
Traceback (most recent call last):
  File "/home/sphuber/.virtualenvs/aiida_dev/bin/launch_misc_cif_import", line 11, in <module>
    load_entry_point('aiida-codtools', 'console_scripts', 'launch_misc_cif_import')()
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sphuber/code/aiida/env/dev/aiida-codtools/aiida_codtools/cli/misc/cif_import.py", line 146, in launch
    for entry in query_results:
  File "/home/sphuber/code/aiida/env/dev/aiida-core/aiida/tools/dbimporters/baseclasses.py", line 107, in next
    if pos >= 0 and pos < len(self._results):
  File "/home/sphuber/code/aiida/env/dev/aiida-core/aiida/tools/dbimporters/baseclasses.py", line 122, in __len__
    return len(self._results)
AttributeError: 'IcsdSearchResults' object has no attribute '_results'
```

**Comment by sphuber** [comment]
Fixed in PR #1288
