### ISSUE TITLE
DetachedInstanceError accessing dbnode attributes on SqlAlchemy

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1292]
When running a workchain on the latest `workflows` branch at some point a `DetachedInstanceError` is raised when `self.dbnode.uuid` is called. This is the full stack trace:

```
03/17/2018 02:21:53 PM, aiida.orm.implementation.general.calculation.work.WorkCalculation: [REPORT] [149|PwBaseWorkChain|on_except]: Traceback (most recent call last):
  File "/home/sphuber/.virtualenvs/aiida_plugin/src/plumpy/plumpy/events.py", line 119, in _run
    self._callback(*self._args, **self._kwargs)
  File "/home/sphuber/code/aiida/env/plugin/aiida-core/aiida/work/persistence.py", line 104, in save_checkpoint
    bundle = Bundle(process, class_loader.CLASS_LOADER)
  File "/home/sphuber/.virtualenvs/aiida_plugin/src/plumpy/plumpy/persistence.py", line 48, in __init__
    self.update(savable.save(class_loader_=class_loader_))
  File "/home/sphuber/.virtualenvs/aiida_plugin/src/plumpy/plumpy/persistence.py", line 464, in save
    base.call_with_super_check(self.save_instance_state, out_state)
  File "/home/sphuber/.virtualenvs/aiida_plugin/src/plumpy/plumpy/base/utils.py", line 33, in call_with_super_check
    fn(*args, **kwargs)
  File "/home/sphuber/code/aiida/env/plugin/aiida-core/aiida/work/workchain.py", line 62, in save_instance_state
    out_state[self._CONTEXT] = serialize_data(self.ctx)
  File "/home/sphuber/code/aiida/env/plugin/aiida-core/aiida/utils/serialize.py", line 56, in serialize_data
    return {encode_key(key): serialize_data(value) for key, value in data.iteritems()}
  File "/home/sphuber/code/aiida/env/plugin/aiida-core/aiida/utils/serialize.py", line 56, in <dictcomp>
    return {encode_key(key): serialize_data(value) for key, value in data.iteritems()}
  File "/home/sphuber/code/aiida/env/plugin/aiida-core/aiida/utils/serialize.py", line 56, in serialize_data
    return {encode_key(key): serialize_data(value) for key, value in data.iteritems()}
  File "/home/sphuber/code/aiida/env/plugin/aiida-core/aiida/utils/serialize.py", line 56, in <dictcomp>
    return {encode_key(key): serialize_data(value) for key, value in data.iteritems()}
  File "/home/sphuber/code/aiida/env/plugin/aiida-core/aiida/utils/serialize.py", line 52, in serialize_data
    return '{}{}'.format(_PREFIX_VALUE_NODE, data.uuid)
  File "/home/sphuber/code/aiida/env/plugin/aiida-core/aiida/orm/implementation/sqlalchemy/node.py", line 677, in uuid
    return unicode(self.dbnode.uuid)
  File "/home/sphuber/.virtualenvs/aiida_plugin/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/sphuber/.virtualenvs/aiida_plugin/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
    value = state._load_expired(state, passive)
  File "/home/sphuber/.virtualenvs/aiida_plugin/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 474, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/home/sphuber/.virtualenvs/aiida_plugin/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 610, in load_scalar_attributes
    (state_str(state)))
DetachedInstanceError: Instance <DbNode at 0x7fb2b5c0acd0> is not bound to a Session; attribute refresh operation cannot proceed
```

This happens when the persister tries to persist the context of the workchain, so it serialized the contents of the context, which then needs to get the uuid of a `Node` which sequentially trigger the error.

**Comment by sphuber** [comment]
This is a manifestation of a deeper problem related to the copying and deep copying of Nodes that is described in more detail in issue #1301
