### ISSUE TITLE
Process ends up in Excepted state when calculation is SUBMISSIONFAILED

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1363]
When the `JobCalculation` ends up in `SUBMISSIONFAILED` the `Process` will transition to `FINISHED` state, but during this transition an exception occurs, causing the transition to fail and the `Process` will end up in the state `EXCEPTED` instead.

```
[76|JobProcess_aiida.orm.calculation.job.simpleplugins.templatereplacer.TemplatereplacerCalculation|on_except]: Traceback (most recent call last):
  File "/home/travis/build/aiidateam/aiida_core/aiida/work/job_processes.py", line 249, in action_command
    job_done = yield self._task
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/travis/virtualenv/python2.7.14/src/kiwipy/kiwipy/futures.py", line 43, in result
    return super(Future, self).result(timeout=0.)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/travis/build/aiidateam/aiida_core/aiida/work/job_processes.py", line 66, in _execute
    self.set_result(self.execute(transport))
  File "/home/travis/build/aiidateam/aiida_core/aiida/work/job_processes.py", line 99, in execute
    found_jobs = scheduler.getJobs(**kwargs)
  File "/home/travis/build/aiidateam/aiida_core/aiida/scheduler/__init__.py", line 343, in getJobs
    retval, stdout, stderr = self.transport.exec_command_wait(self._get_joblist_command(jobs=jobs, user=user))
  File "/home/travis/build/aiidateam/aiida_core/aiida/scheduler/plugins/pbsbaseclasses.py", line 162, in _get_joblist_command
    command.append('{}'.format(' '.join(escape_for_bash(j) for j in jobs)))
  File "/home/travis/build/aiidateam/aiida_core/aiida/scheduler/plugins/pbsbaseclasses.py", line 162, in <genexpr>
    command.append('{}'.format(' '.join(escape_for_bash(j) for j in jobs)))
  File "/home/travis/build/aiidateam/aiida_core/aiida/common/utils.py", line 163, in escape_for_bash
    escaped_quotes = str_to_escape.replace("'", """'"'"'""")
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by sphuber** [comment]
Fixed in #1401
