### ISSUE TITLE
verdi work list can throw an exception if an entry does not have process state yet

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1365]
Calling `verdi work list` can except with the following stack trace:

```
Traceback (most recent call last):
  File "/home/aiida/.virtualenvs/aiida_sdb/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/verdilib.py", line 1040, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/verdilib.py", line 1025, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/baseclass.py", line 221, in run
    function_to_call(*args[1:])
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/commands/work.py", line 48, in cli
    verdi()
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/commands/work.py", line 188, in do_list
    value = projection_format_map[p](calculation)
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/commands/work.py", line 148, in <lambda>
    'state': lambda value: '{} | {}'.format(value[PROCESS_STATE_KEY].capitalize(), value[FINISH_STATUS_KEY]),
```

This can occur if one of the retrieved entries does not yet have a `process_state` attribute, which can happen when it is just created. Usually calling `verdi work list` again solves the issue, but obviously this is not nice and we should simply check in the lambda if the `process_state` attribute is presented or else just print `None`

**Comment by sphuber** [comment]
Fixed in #1368
