### ISSUE TITLE
Various kinds of stuck calculations

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1426]
With the new daemon, I'm experiencing different kinds of stuck / failing calculations: 

- Calculations which except due to being submitted while in ``TOSUBMIT`` state (instead of ``NEW``).
- Calculations stuck in ``RETRIEVING``, with the process being either ``Waiting`` or ``Running``.
- Calculations stuck indefinitely in ``WITHSCHEDULER``, with the process being in ``Waiting``.

These issues might be due to problems with starting / stopping the daemon or individual workers. Since I don't have a good way to reproduce them yet, I will continue to investigate it and update the issue.

A wild guess: It appears ``circus`` has a ``graceful_timeout`` of thirty seconds, after which (I think) the process will be ``SIGKILL``ed. Maybe that produces some of these issues?

**Comment by AntimoMarrazzo** [comment]
Here we have a similar case:
15842  18m ago     Waiting | None   quantumespresso.pw  daint-mc    RETRIEVING | DONE
with the error:
07/13/2018 10:36:19 AM <84526> aiida.aiida_quantumespresso.calculations.pw.PwCalculation: [REPORT] [15837|JobProcess_aiida_quantumespresso.calculations.pw:PwCalculation|on_except]: Traceback (most recent call last):
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/process_states.py", line 227, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/home/aiida/code/aiida/env/***/aiida_core/aiida/work/job_processes.py", line 530, in retrieved
    exit_code = execmanager.parse_results(self.calc, retrieved_temporary_folder)
  File "/home/aiida/code/aiida/env/***/aiida_core/aiida/daemon/execmanager.py", line 409, in parse_results
    exit_code, new_nodes_tuple = parser.parse_from_calc(retrieved_temporary_folder)
  File "/home/aiida/code/aiida/env/***/aiida_core/aiida/parsers/parser.py", line 89, in parse_from_calc
    return self.parse_with_retrieved(retrieved)
  File "/home/aiida/code/aiida/env/***/aiida-quantumespresso/aiida_quantumespresso/parsers/pw.py", line 96, in parse_with_retrieved
    out_dict, trajectory_data, structure_data, bands_data, raw_successful = parse_raw_output(*parsing_args)
  File "/home/aiida/code/aiida/env/***/aiida-quantumespresso/aiida_quantumespresso/parsers/raw_parser_pw.py", line 67, in parse_raw_output
    xml_data, structure_data, bands_data = parse_pw_xml_output(xml_lines, dir_with_bands)
  File "/home/aiida/code/aiida/env/***/aiida-quantumespresso/aiida_quantumespresso/parsers/raw_parser_pw.py", line 1044, in parse_pw_xml_output
    raise QEOutputParsingError('Error parsing card {}'.format(tagname))
QEOutputParsingError: Error parsing card K-POINT.1

Restarting the daemon it gets crazy with other errors:
07/13/2018 10:55:21 AM <84526> tornado.application: [ERROR] Exception in callback <functools.partial object at 0x7f905317f470>
Traceback (most recent call last):
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aiida/.virtualenvs/**/lib/python2.7/site-packages/plumpy/processes.py", line 983, in step_until_terminated
    yield self.step()
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/processes.py", line 959, in step
    self.transition_to(process_states.ProcessState.KILLED, None)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 326, in transition_to
    *sys.exc_info()[1:])
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 339, in transition_failed
    raise_(type(exception), exception, trace)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 308, in transition_to
    self._enter_next_state(new_state)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 373, in _enter_next_state
    self._fire_state_event(StateEventHook.ENTERING_STATE, next_state)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 287, in _fire_state_event
    callback(self, hook, state)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/processes.py", line 281, in <lambda>
    lambda _s, _h, state: self.on_entering(state))
  File "/home/aiida/code/aiida/env/***/aiida_core/aiida/work/processes.py", line 209, in on_entering
    super(Process, self).on_entering(state)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/processes.py", line 628, in on_entering
    call_with_super_check(self.on_kill, state.msg)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/base/utils.py", line 29, in call_with_super_check
    fn(*args, **kwargs)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/base/utils.py", line 16, in new_fn
    fn(self, *args, **kwargs)
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/plumpy/processes.py", line 760, in on_kill
    self.future().set_exception(exceptions.KilledError(msg))
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/concurrent.py", line 286, in set_exception
    getattr(exception, '__traceback__', None)))
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/concurrent.py", line 309, in set_exc_info
    self._set_done()
  File "/home/aiida/.virtualenvs/***/lib/python2.7/site-packages/tornado/concurrent.py", line 323, in _set_done
    for cb in self._callbacks:
TypeError: 'NoneType' object is not iterable
~

**Comment by AntimoMarrazzo** [comment]
If we restart again the daemon we get that the daemon does not fine the tmp folder to parse the bands.  No such file or directory: '/tmp/tmpxy4YYy/./K00001/eigenval.xml'
Probably when the daemon is stopped the tmp folder is cleaned, and when it starts again it tries to look again for those files...
