### ISSUE TITLE
'verdi calculation gotocomputer' broken

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1430]
Traceback: 

```
Loading environment...
Traceback (most recent call last):
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/cmdline/verdilib.py", line 1056, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/cmdline/verdilib.py", line 1041, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/cmdline/baseclass.py", line 233, in run
    function_to_call(*args[1:])
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/cmdline/commands/calculation.py", line 113, in calculation_gotocomputer
    t = calc._get_transport()
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 1364, in _get_transport
    return self._get_authinfo().get_transport()
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 1358, in _get_authinfo
    return self.backend.authinfos.get(computer=computer, aiidauser=self.get_user())
TypeError: get() got an unexpected keyword argument 'aiidauser'
```

It seems the interface for ``authinfos.get()`` was changed, without changing the call.

**Comment by greschd** [comment]
Fixed in #1427, as far as I can tell.
