### ISSUE TITLE
Daemon worker crashes when a process doesn't have a checkpoint

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1441]
I think the worker should just log the error and continue. If the worker crashes, it might create problems with the consistency of the other processes that the worker is working on.

Traceback:
```
Traceback (most recent call last):
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/cmdline/verdilib.py", line 1056, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/cmdline/verdilib.py", line 1041, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/cmdline/baseclass.py", line 233, in run
    function_to_call(*args[1:])
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/cmdline/utils/decorators.py", line 52, in decorated_function
    return function(*args, **kwargs)
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/cmdline/commands/devel.py", line 375, in run_daemon
    start_daemon()
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/daemon/runner.py", line 47, in start_daemon
    runner.start()
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/work/runners.py", line 157, in start
    self._loop.start()
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/local/lib/python2.7/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 395, in _handle_events
    self._handle_read()
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 449, in _handle_read
    self._on_data_available(data)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/local/lib/python2.7/site-packages/pika/connection.py", line 1938, in _on_data_available
    self._process_frame(frame_value)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/local/lib/python2.7/site-packages/pika/connection.py", line 2072, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/local/lib/python2.7/site-packages/pika/connection.py", line 1479, in _deliver_frame_to_channel
    self._channels[value.channel_number]._handle_content_frame(value)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/local/lib/python2.7/site-packages/pika/channel.py", line 996, in _handle_content_frame
    self._on_deliver(*response)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/local/lib/python2.7/site-packages/pika/channel.py", line 1125, in _on_deliver
    header_frame.properties, body)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/local/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/src/kiwipy/kiwipy/rmq/tasks.py", line 136, in _on_task
    result = subscriber(task)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/src/plumpy/plumpy/process_comms.py", line 216, in __call__
    return self._continue(task)
  File "/home/greschd/.virtualenvs/aiida_tbextraction_workflows/src/plumpy/plumpy/process_comms.py", line 243, in _continue
    saved_state = self._persister.load_checkpoint(task[PID_KEY], tag)
  File "/media/greschd/large_data/projects/aiida_tbextraction_workflows/source/aiida_core/aiida/work/persistence.py", line 129, in load_checkpoint
    raise PersistenceError('Calculation<{}> does not have a saved checkpoint'.format(calculation.pk))
aiida.work.persistence.PersistenceError: Calculation<70621> does not have a saved checkpoint
```

**Comment by sphuber** [comment]
Fixed in #1442
