### ISSUE TITLE
0.12.0 submission problem

### ISSUE THREAD

**Issue by quanshengwu** [aiidateam/aiida_core#1497]
Hi,
I meet a problem when submitting the job with aiida. 
(aiidapy-new) quantumespresso$runaiida  test_pw.py --send pw.x6.2-itplin@itplin
Using the pseudo for Ba from DB: 3187
Using the pseudo for Ti from DB: 3188
Using the pseudo for O from DB: 3189
created calculation; calc=Calculation(uuid='faf75f2c-0b27-46cd-ae6e-8944cb2639ce') # ID=3194
05/08/2018 01:50:39 PM <4947> pika.callback: [ERROR] Calling <bound method TornadoConnection._on_connection_error of <TornadoConnection INIT socket=None params=<URLParameters host=127.0.0.1 port=5672 virtual_host=/ ssl=False>>> for "0:_on_connection_error" failed
Traceback (most recent call last):
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/pika/connection.py", line 1768, in _on_connection_error
    self.params.connection_attempts)
AMQPConnectionError: Connection to 127.0.0.1:5672 failed: [Errno 61] Connection refused
05/08/2018 01:50:39 PM <4947> tornado.application: [ERROR] Exception in callback <functools.partial object at 0x10c0432b8>
Traceback (most recent call last):
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/pika/connection.py", line 1836, in _on_connect_timer
    error)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/pika/connection.py", line 1768, in _on_connection_error
    self.params.connection_attempts)
AMQPConnectionError: Connection to 127.0.0.1:5672 failed: [Errno 61] Connection refused

The computetest works fine.
(aiidapy-new) quantumespresso$verdi computer test itplin
Testing computer 'itplin' for user blablabla...
> Testing connection...
> Getting job list...
  `-> OK, 63 jobs found in the queue.
> Creating a temporary file in the work directory...
  `-> Getting the remote user name...
      [remote username: qwu]
      [Checking/creating work directory: /export/scratch/wuq/aiida-scratch]
  `-> Creating the file tmpQUttuK...
  `-> Checking if the file has been created...
      [OK]
  `-> Retrieving the file and checking its content...
      [Retrieved]
      [Content OK]
  `-> Removing the file...
  [Deleted successfully]
Test completed (all 3 tests succeeded)

**Comment by sphuber** [comment]
It seems you have not actually checked out version `0.12.0` but the `develop` branch. Since we do not update the version number until the release, the version number in `aiida.__init__.py` there will still show `0.12.0`. I know it is the develop branch because the error comes from `pika` which is not part of the official `0.12.0` release. Unfortunately, since you migrated your database to the version of the develop branch, which is newer than the schema in `v0.12.0`, so you won't be able to revert, unless you made a backup of  course as advised in the docs before upgrading. If this is not the case, you can simply finalize the migration by installing RabbitMQ on your system:

http://aiida-core.readthedocs.io/en/latest/install/details/os.html

And then by applying the following steps to your workchains and scripts:

http://aiida-core.readthedocs.io/en/latest/concepts/workflows.html#upgrading-workchains-from-pre-v1-0-0

**Comment by quanshengwu** [comment]
I still don't understand the problem. Maybe it is not the problem of v0.12.0. Is it possible to solve it within the develop branch? You are right.  After checkout the latest develop branch, I already immigrated the database to the latest version.

**Comment by quanshengwu** [comment]
I am now working on installing RabbitMQ, I hope it would fix the problem.

**Comment by sphuber** [comment]
Make sure that you also reinstall aiida `pip install -e .` with the necessary options, to install the latest dependencies.

**Comment by quanshengwu** [comment]
Yes, I did reinstall aiida with "pip install -e ." 
I also installed RabbitMQ with "brew install RabbitMQ", the server was started with "rabbitmq-server". 

However, I still can't submit the job to the remote machine. This time the error is different from the one before installation of RabbitMQ.

`Using the pseudo for Ba from DB: 3187
Using the pseudo for Ti from DB: 3188
Using the pseudo for O from DB: 3189
created calculation; calc=Calculation(uuid='7c5253a1-c100-4f70-9522-bb7f6e405397') # ID=3214
Traceback (most recent call last):
  File "/Users/user/aiidapy-new/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/cmdline/verdilib.py", line 1056, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/cmdline/verdilib.py", line 1041, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/cmdline/verdilib.py", line 886, in run
    exec (f, globals_dict)
  File "test_pw.py", line 206, in <module>
    calc.submit()
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 1381, in submit
    submit(ContinueJobCalculation, _calc=self)
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/work/launch.py", line 26, in submit
    return runner.submit(process, **inputs)
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/work/runners.py", line 193, in submit
    process = self.instantiate_process(process, *args, **inputs)
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/work/runners.py", line 177, in instantiate_process
    process = process_class(runner=self, inputs=inputs)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 188, in __call__
    inst.transition_to(inst.create_initial_state())
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 326, in transition_to
    self.transition_failed(initial_state_label, label, *sys.exc_info()[1:])
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 339, in transition_failed
    raise_(type(exception), exception, trace)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 310, in transition_to
    self._enter_next_state(new_state)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 371, in _enter_next_state
    self._fire_state_event(StateEventHook.ENTERING_STATE, next_state)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 289, in _fire_state_event
    callback(self, hook, state)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/plumpy/processes.py", line 274, in <lambda>
    lambda _s, _h, state: self.on_entering(state))
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/work/processes.py", line 194, in on_entering
    super(Process, self).on_entering(state)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/plumpy/processes.py", line 603, in on_entering
    call_with_super_check(self.on_create)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/plumpy/base/utils.py", line 29, in call_with_super_check
    fn(*args, **kwargs)
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/work/processes.py", line 103, in on_create
    if self._parent_pid is None and not plumpy.stack.is_empty():
AttributeError: 'module' object has no attribute 'stack'`

**Comment by sphuber** [comment]
Have you restarted the daemon after installing? Please try to run `verdi daemon restart --reset` and see if that helps

**Comment by quanshengwu** [comment]
@sphuber  I am sorry it doesn't work either...

(aiidapy-new) quantumespresso$verdi daemon stop
vProfile: quicksetup
Waiting for the daemon to shut down... eOK
(aiidapy-new) quantumespresso$verdi daemon start
Starting the daemon... \-RUNNING
r(aiidapy-new) quantumespresso$runaiida test_pw.py --send
Pass as further parameter a valid code label.
Valid labels with a quantumespresso.pw executable are:
* pw.x6.1-itplin39@itplin39
* pw.x6.2-itplin39@itplin39
(aiidapy-new) quantumespresso$runaiida test_pw.py --send pw.x6.2-itplin39
Using the pseudo for Ba from DB: 3187
Using the pseudo for Ti from DB: 3188
Using the pseudo for O from DB: 3189
created calculation; calc=Calculation(uuid='e3f08368-2cd8-404e-8f4d-51bd4bb7f4cf') # ID=3244
Traceback (most recent call last):
  File "/Users/user/aiidapy-new/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/cmdline/verdilib.py", line 1056, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/Users/user/quan/work/workplace/AiiDA-new/aiida_core/aiida/cmdline/verdilib.py", line 1041, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])

**Comment by quanshengwu** [comment]
Thank Sebastiaan. This problem was fixed. Basically, this problem was caused by some unknown changes of Aiida by myself. Then the Daemon is not compatible with the version I have.  With the help of Sebastiaan, the following steps were used. 

1. Install RabbitMQ follow the documentation of Aiida. 
2.Start the RabbitMQ server. 
3. git pull the latest version of Aiida (0.12.0 at present). "git pull origin develop'
