### ISSUE TITLE
verdi node delete throws exception

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1563]
The following exception:

```
I will delete 165 nodes
Traceback (most recent call last):
  File "/home/aiida/.virtualenvs/aiida_sdb/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/verdilib.py", line 1056, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/verdilib.py", line 1041, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/baseclass.py", line 150, in run
    function_to_call(*args[1:])
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/commands/node.py", line 362, in run
    dry_run=parsed_args.dry_run, verbosity=parsed_args.verbosity)
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/utils/delete_nodes.py", line 113, in delete_nodes
    's' if len(calculation_pks_losing_created) > 1 else '',
UnboundLocalError: local variable 'calculation_pks_losing_created' referenced before assignment
```

This is due to a typo and appears both in `release_v0.12.1` and `develop` and should be fixed in both

**Comment by sphuber** [comment]
Fixed in PR #1564
