### ISSUE TITLE
Legacy Workflows: sqla implementation's get_report fails if report does not exist

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#1671]
## Expected behaviour
`get_report()` should return a list of strings or empty list

```
from aiida.workflows.test import WFSimpleWithSubWf
workflow = WFSimpleWithSubWf()
workflow.store()
workflow.start()
report = workflow.get_report()  # should return a list of strings or empty list if there are no reports
```

## Observed behaviour
`get_report()` fails in the following case

### Test
Shortened for the sake of legibility:

```
class TestVerdiLegacyWorkflow(AiidaTestCase):

    @classmethod
    def setUpClass(cls):
        from aiida.workflows.test import WFTestEmpty, WFTestSimpleWithSubWF

        super(TestVerdiLegacyWorkflow, cls).setUpClass()
        cls.runner = CliRunner()

        cls.super_workflow = WFTestSimpleWithSubWF()
        cls.super_workflow.store()
        cls.super_workflow.start()

    def test_workflow_report(self):
        result = self.runner.invoke(workflow_report, [str(self.super_workflow.uuid)])
        self.assertIsNone(result.exception, msg=debug_msg(result))
        self.assertIn(str(self.super_workflow.pk), result.output)

```

### Output

```
======================================================================
FAIL: test_workflow_report (aiida.backends.tests.cmdline.commands.test_workflow.TestVerdiLegacyWorkflow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ricohaeuselmann/Code/aiida-fork/aiida/backends/tests/cmdline/commands/test_workflow.py", line 68, in test_workflow_report
    self.assertIsNone(result.exception, msg=debug_msg(result))
AssertionError: Traceback (most recent call last):
  File "/Users/ricohaeuselmann/.venvwrap/aiida-dev-1/lib/python2.7/site-packages/click/testing.py", line 279, in invoke
    prog_name=self.get_default_prog_name(cli), **extra)
  File "/Users/ricohaeuselmann/.venvwrap/aiida-dev-1/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/ricohaeuselmann/.venvwrap/aiida-dev-1/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ricohaeuselmann/.venvwrap/aiida-dev-1/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/ricohaeuselmann/Code/aiida-fork/aiida/cmdline/utils/decorators.py", line 183, in decorated_function
    return function(*args, **kwargs)
  File "/Users/ricohaeuselmann/Code/aiida-fork/aiida/cmdline/commands/workflow.py", line 130, in workflow_report
    echo.echo('\n'.join(workflow.get_report()))
  File "/Users/ricohaeuselmann/Code/aiida-fork/aiida/orm/implementation/sqlalchemy/workflow.py", line 499, in get_report
    return self.dbworkflowinstance.report.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by sphuber** [comment]
Fixed in PR #1668
