### ISSUE TITLE
python3:pip install error

### ISSUE THREAD

**Issue by BaozCWJ** [aiidateam/aiida_core#1727]
C:\Users\Thinkpad>pip install aiida
Collecting aiida
  Using cached https://files.pythonhosted.org/packages/8d/c9/e827f586ac085f11037a525497644cf851e9f20944022ada760db0a53e69/aiida-0.12.1.tar.gz
Collecting aiida-core==0.12.1 (from aiida)
  Using cached https://files.pythonhosted.org/packages/ea/02/192df4afb553bf1b9bcf5d421b1cfeae2b201ec3e29d6592d17d9fbc4820/aiida-core-0.12.1.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Thinkpad\AppData\Local\Temp\pip-install-70di71fj\aiida-core\setup.py", line 30
        print 'Could not import pip, which is required for installation'
                                                                       ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Thinkpad\AppData\Local\Temp\pip-install-70di71fj\aiida-core\

Before installing this package, I can successfully use "pip install " to install another package, so I don't think that should be the problem of pip.

**Comment by dev-zero** [comment]
you can apply the commit https://github.com/aiidateam/aiida_core/pull/1682/commits/28a22e6b1c2afe602372da376ee203a09db44de1 from my PR #1682 on a git-clone of `aiida_core` to at least be able to the dependencies, but Python 3 is currently not supported at all.
