### ISSUE TITLE
socket timed out. ssh transport

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida_core#1728]
I very often run into the error below for calculations, which will put them into Excepted. Which I guess comes from a ssh connection that is timed out (because whatever) and aiida tries to use this connection. This error should be caught somewhere and a new connection opened I guess. 
It also might be that playing with an ssh config might help a bit.
@muhrin if this error should be caught in plumpy and then something cleaned up and reraised. Please forward this issue. 

aiida_core: develop
plumpy: 10.3
```
|   [136963|JobProcess_aiida_fleur.calculation.fleur:FleurCalculation|on_except]: Traceback (most recent call last):
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/plumpy/processes.py", line 466, in _process_scope
|       yield
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/tornado/stack_context.py", line 316, in wrapped
|       ret = fn(*args, **kwargs)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/transports.py", line 79, in _do_callback
|       with entry.transport:
|     File "/Users/broeder/aiida/github/aiida_core/aiida/transport/transport.py", line 61, in __enter__
|       self.open()
|     File "/Users/broeder/aiida/github/aiida_core/aiida/transport/plugins/ssh.py", line 471, in open
|       self._client.connect(self._machine, **connection_arguments)
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/client.py", line 338, in connect
|       retry_on_signal(lambda: sock.connect(addr))
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/util.py", line 279, in retry_on_signal
|       return function()
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/client.py", line 338, in <lambda>
|       retry_on_signal(lambda: sock.connect(addr))
|     File "/usr/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
|       return getattr(self._sock,name)(*args)
|   error: [Errno 60] Operation timed out
```

**Comment by broeder-j** [comment]
Here are some further ssh errors that occur now:

```
*** 137154 [scf: fleur run 1]: SUBMISSIONFAILED
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> ERROR at 2018-07-08 08:11:21.343821+00:00
|   Submission of calc 137154 failed, check also the log file! Traceback: Traceback (most recent call last):
|     File "/Users/broeder/aiida/github/aiida_core/aiida/daemon/execmanager.py", line 169, in submit_calc
|       t.chdir(remote_working_directory)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/transport/plugins/ssh.py", line 547, in chdir
|       self.sftp.chdir(path)
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/sftp_client.py", line 631, in chdir
|       self._cwd = b(self.normalize(path))
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/sftp_client.py", line 599, in normalize
|       t, msg = self._request(CMD_REALPATH, path)
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/sftp_client.py", line 780, in _request
|       return self._read_response(num)
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/sftp_client.py", line 812, in _read_response
|       raise SSHException('Server connection dropped: {}'.format(e))
|   SSHException: Server connection dropped: 

** 137973 [scf: fleur run 2]: FAILED
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> REPORT at 2018-07-08 08:15:24.650276+00:00
|   [137973|JobProcess_aiida_fleur.calculation.fleur:FleurCalculation|on_except]: Traceback (most recent call last):
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/job_processes.py", line 231, in execute
|       job_done = yield self._task
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
|       value = future.result()
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/kiwipy/futures.py", line 43, in result
|       return super(Future, self).result(timeout=0.)
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
|       raise_exc_info(self._exc_info)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/job_processes.py", line 59, in _execute
|       self.set_result(self.execute(transport))
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/job_processes.py", line 98, in execute
|       found_jobs = scheduler.getJobs(**kwargs)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/scheduler/__init__.py", line 343, in getJobs
|       retval, stdout, stderr = self.transport.exec_command_wait(self._get_joblist_command(jobs=jobs, user=user))
|     File "/Users/broeder/aiida/github/aiida_core/aiida/transport/plugins/ssh.py", line 1312, in exec_command_wait
|       ssh_stdin, stdout, stderr, channel = self._exec_command_internal(command, combine_stderr, bufsize=bufsize)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/transport/plugins/ssh.py", line 1274, in _exec_command_internal
|       channel = self.sshclient.get_transport().open_session()
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/transport.py", line 767, in open_session
|       timeout=timeout)
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/transport.py", line 854, in open_channel
|       raise SSHException('SSH session not active')
|   SSHException: SSH session not active


*** 138003 [scf: fleur run 2]: FAILED
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> REPORT at 2018-07-08 08:41:00.043777+00:00
|   [138003|JobProcess_aiida_fleur.calculation.fleur:FleurCalculation|on_except]: Traceback (most recent call last):
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/job_processes.py", line 231, in execute
|       job_done = yield self._task
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
|       value = future.result()
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/kiwipy/futures.py", line 43, in result
|       return super(Future, self).result(timeout=0.)
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
|       raise_exc_info(self._exc_info)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/job_processes.py", line 59, in _execute
|       self.set_result(self.execute(transport))
|     File "/Users/broeder/aiida/github/aiida_core/aiida/work/job_processes.py", line 98, in execute
|       found_jobs = scheduler.getJobs(**kwargs)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/scheduler/__init__.py", line 343, in getJobs
|       retval, stdout, stderr = self.transport.exec_command_wait(self._get_joblist_command(jobs=jobs, user=user))
|     File "/Users/broeder/aiida/github/aiida_core/aiida/transport/plugins/ssh.py", line 1312, in exec_command_wait
|       ssh_stdin, stdout, stderr, channel = self._exec_command_internal(command, combine_stderr, bufsize=bufsize)
|     File "/Users/broeder/aiida/github/aiida_core/aiida/transport/plugins/ssh.py", line 1274, in _exec_command_internal
|       channel = self.sshclient.get_transport().open_session()
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/transport.py", line 767, in open_session
|       timeout=timeout)
|     File "/Users/broeder/aiida/github/envs/env_aiida_new/lib/python2.7/site-packages/paramiko/transport.py", line 891, in open_channel
|       raise e
|   error: [Errno 50] Network is down
```

**Comment by giovannipizzi** [comment]
We have the same problems (with the same versions).

I think there are two parts in this:
- URGENT: when an error like this is thrown, especially during a simple check for the scheduler state, it should just be ignored (or in the "worst" case set the computer to disabled, maybe after a few trials) but not except.
- Less urgent but still important: understand why we get so many SSH errors. It looks strange to me that we get so many. Either this is common and before we weren't noticing it, or now the way we call paramiko has some problems (e.g. we might be trying to keep the SSH connection open, and when we open a new channel (e.g. with `self.sshclient.get_transport().open_session()`) we get an error if it the server dropped the connection.

**Comment by broeder-j** [comment]
Update:
1. Some ssh errors occurred because I had in my ssh config a second different account for that machine.
so sometimes when checking or receiving, Paramiko might have tried to use that old account, since the config is read. Therefore, my fault.

2. Firewall issues. I increased the connection time constant (_DEFAULT_SAFE_OPEN_INTERVAL) which decreased the lost connections.

3.  On a second machine they had some problems, the scheduler was unresponsive, 
executing scheduler commands forever. Therefore, a job list or job submit command did not return anything and did not finish. Leaving AiiDA jobs in submitting and causing transport errors even through the jobs where executed. In such cases there is not much, one can do from the AiiDA side.


Through timeouts still remain occasionally. (the rate might also increase with the number of jobs managed, felt like it.)
In older AiiDA versions the only error on transport was during submission (very rare on retrieval).
Now, a calculation might except, if aiida gets an error due a execute a 'job list' command or other  transport failure. This, we should make more robust, like Giovanni suggested.

Also somehow AiiDA needed all resources on the machine it was running on when the connections were lost, which seems a bit strange to me (for around 100 jobs), but currently I do not know if this is connected to transport or daemon worker code.

**Comment by muhrin** [comment]
Closing this issue.  It's unclear what the source is but the following is possible:

1) The SSH connection itself had problems beyond our control.  This is now (in develop) being dealt with gracefully by retrying with an exponential backoff and going into a paused state if that fails.

2) The file is large and paramiko is having problems doing the SCP.  We will continue to monior this in #188 but have no fix at the moment.

If you feel there is another (non-generic) reason why this could have arisen then please open a specific issue for that and we'll look at it.
