### ISSUE TITLE
on_entering(state) error / Process termination problem, Daemon hangs 

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida_core#1818]
I am testing the new Daemon, with simple calculations on localhost.

The calculations are submited via the direct scheduler using local transport. Some ran fine, then the daemon encountered this error below (calculation exit code 200), I have no idea what the reason here is, sorry. Maybe @muhrin or @sphuber have a clue. 

There was some error (where none should be, the calculation code finished fine), plum tried to kill/end the process, which fails.
The bad thing is it causes all RMQ connections to fail afterwards forever (from the client side), bringing the daemon in a 'somewhat stuck state' where no calculations are processed anymore, restarting the daemon ends up in same state again.

I realized my Rabbitmq version was quite old, so installed the recent version, first processed calculation run into it again.

aiida version: develop
plumpy: aiida branch
rabbitmq: 3.7.7-1 (Old rmq version before 3.5.x)
linux mint: 18.3
daemon: one worker, aiida defaults

Here is a full traceback from the log.
```
07/30/2018 11:59:44 AM <7155> pika.adapters.base_connection: [ERROR] Error event 25, None
07/30/2018 11:59:44 AM <7155> pika.adapters.base_connection: [CRITICAL] Tried to handle an error where no error existed
07/30/2018 11:59:44 AM <7155> aiida.daemon.runner: [DEBUG] Ticking the legacy workflows
07/30/2018 11:59:44 AM <7155> aiida.daemon.runner: [DEBUG] Checking for workflows to manage
07/30/2018 11:59:44 AM <7155> aiida.daemon.runner: [DEBUG] Running execute_steps
07/30/2018 11:59:44 AM <7155> aiida.workflowmanager: [DEBUG] Querying the worflow DB
07/30/2018 11:59:44 AM <7155> pika.adapters.base_connection: [ERROR] Socket Error: 104
07/30/2018 11:59:44 AM <7155> aiida.aiida_fleur.calculation.fleurinputgen.FleurinputgenCalculation: [INFO] Kill Process<449128>
07/30/2018 11:59:44 AM <7155> tornado.application: [ERROR] Future exception was never retrieved: KillInterruption
07/30/2018 11:59:44 AM <7155> tornado.application: [ERROR] Exception in callback <functools.partial object at 0x7f3c6806e0a8>
Traceback (most recent call last):
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/broeder/aiida/github/plumpy/plumpy/processes.py", line 983, in step_until_terminated
    yield self.step()
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/broeder/aiida/github/plumpy/plumpy/processes.py", line 959, in step
    self.transition_to(process_states.ProcessState.KILLED, None)
  File "/home/broeder/aiida/github/plumpy/plumpy/base/state_machine.py", line 326, in transition_to
    *sys.exc_info()[1:])
  File "/home/broeder/aiida/github/plumpy/plumpy/base/state_machine.py", line 339, in transition_failed
    raise_(type(exception), exception, trace)
  File "/home/broeder/aiida/github/plumpy/plumpy/base/state_machine.py", line 308, in transition_to
    self._enter_next_state(new_state)
  File "/home/broeder/aiida/github/plumpy/plumpy/base/state_machine.py", line 373, in _enter_next_state
    self._fire_state_event(StateEventHook.ENTERING_STATE, next_state)
  File "/home/broeder/aiida/github/plumpy/plumpy/base/state_machine.py", line 287, in _fire_state_event
    callback(self, hook, state)
  File "/home/broeder/aiida/github/plumpy/plumpy/processes.py", line 281, in <lambda>
    lambda _s, _h, state: self.on_entering(state))
  File "/home/broeder/aiida/github/aiida_core/aiida/work/processes.py", line 209, in on_entering
    super(Process, self).on_entering(state)
  File "/home/broeder/aiida/github/plumpy/plumpy/processes.py", line 628, in on_entering
    call_with_super_check(self.on_kill, state.msg)
  File "/home/broeder/aiida/github/plumpy/plumpy/base/utils.py", line 29, in call_with_super_check
    fn(*args, **kwargs)
  File "/home/broeder/aiida/github/plumpy/plumpy/base/utils.py", line 16, in new_fn
    fn(self, *args, **kwargs)
  File "/home/broeder/aiida/github/plumpy/plumpy/processes.py", line 760, in on_kill
    self.future().set_exception(exceptions.KilledError(msg))
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/concurrent.py", line 286, in set_exception
    getattr(exception, '__traceback__', None)))
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/concurrent.py", line 309, in set_exc_info
    self._set_done()
  File "/home/broeder/aiida/aiida_env/lib/python2.7/site-packages/tornado/concurrent.py", line 323, in _set_done
    for cb in self._callbacks:
TypeError: 'NoneType' object is not iterable
```
```
449127  38m ago     Finished | 200  fleur.inpgen  local       RETRIEVING | DONE
449128  37m ago     Waiting | None  fleur.inpgen  local       COMPUTED | DONE
449130  36m ago     Finished | 0    fleur.inpgen  local       FINISHED | DONE
449131  36m ago     Finished | 200  fleur.inpgen  local       RETRIEVING | DONE
449132  36m ago     Waiting | None  fleur.inpgen  local       WITHSCHEDULER | None
...
```

**Comment by sphuber** [comment]
This problem is partially known. The socket error 104, stems from the fact that RabbitMQ kills the connection of the daemon worker. This is because the daemon failed to respond to two consecutive heartbeat calls from RabbitMQ. As a result, RabbitMQ assumes it is dead, kills the connection and requeues the tasks that that worker had. Given that you only had one worker, they were not resent to another worker. The daemon worker meanwhile, when it noticed it lost its connection, realizes that RabbitMQ will have requeued the tasks it had, and consequently cancel the futures. This is currently plumbed to call `kill` on the processes, which is why you see the call to kill.

Martin and I are working on this as we speak. The version of RabbitMQ should not be an issue. I am also running 3.5.7. The only problem currently is that the heartbeat interval is set by the server, i.e. RabbitMQ, which has been changed from 580 (pre 3.5.7) to 60 seconds. The client, i.e. in our case `pika`, can change this value, but only to a value smaller than that 60 seconds. Unfortunately, for our case this is way too small. We can change it by changing the server configuration. I have done this in my production setup, and this gets rid of a lot problems, among which the ones you describe. Clearly, however, this is not an ideal situation as we don't want users to have to mess with the RabbitMQ configuration. So in addition we are also working on logic that can deal with lost connections, without causing processes to except. If you are interested, I can send you the configuration file for RMQ so you can run that on your machine.

**Comment by broeder-j** [comment]
Thanks. I will try for now a larger heartbeat. If you changed anything else in your rmq config that changes things for good, i would like to see it.

**Comment by sphuber** [comment]
Duplicate of #1821

**Comment by muhrin** [comment]
@broeder-j @sphuber are you happy for me to close this as being a duplicate?  We now have a working version that should not have this issue but we will be a little careful in merging into develop but expect a merge in the next week.
