### ISSUE TITLE
database issue--FATAL:  password authentication failed for user

### ISSUE THREAD

**Issue by yw-fang** [aiidateam/aiida_core#1831]
Hi,

Yesterday I updated aiida_core (v0.12.1) in the virtual environment through pip, but  I got some fatal errors related to the database, the error information is shown as follows:

> Traceback (most recent call last):
>   File "/home/ywfang-1/miniconda3/envs/aiida/bin/verdi", line 11, in <module>
>     sys.exit(run())
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1050, in run
>     aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1035, in exec_from_cmdline
>     CommandClass.run(*argv[command_position + 1:])
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/aiida/cmdline/baseclass.py", line 217, in run
>     function_to_call(*args[1:])
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/aiida/cmdline/commands/daemon.py", line 114, in daemon_start
>     load_dbenv(process='daemon')
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/aiida/backends/utils.py", line 79, in load_dbenv
>     process=process, profile=profile, *args, **kwargs)
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/aiida/backends/djsite/utils.py", line 27, in load_dbenv
>     check_schema_version()
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/aiida/backends/djsite/utils.py", line 159, in check_schema_version
>     if 'db_dbsetting' not in connection.introspection.table_names():
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/django/db/backends/__init__.py", line 1374, in table_names
>     with self.connection.cursor() as cursor:
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/django/db/backends/__init__.py", line 167, in cursor
>     cursor = utils.CursorWrapper(self._cursor(), self)
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/django/db/backends/__init__.py", line 138, in _cursor
>     self.ensure_connection()
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
>     self.connect()
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
>     self.connect()
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/django/db/backends/__init__.py", line 122, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 130, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/home/ywfang-1/miniconda3/envs/aiida/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> **django.db.utils.OperationalError: FATAL:  password authentication failed for user "aiida1_user"
> FATAL:  password authentication failed for user "aiida1_user"**

The following shows  the setup of my default profile named aiida1:
(aiida) ywfang-1@ywfang:/home/ywfang$ verdi setup aiida1
Setting up profile aiida1.
The following configuration found corresponding to profile aiida1.
Database engine: postgresql_psycopg2
AiiDA Database password: ******
AiiDA Database name: aiida1_database
Database host: localhost
AiiDA backend: django
Database port: 5432
Default user email: fyuewen@gmail.com
AiiDA repository directory: file:///home/ywfang-1/.aiida/repository-aiida1/
AiiDA Database user: aiida1_user

By the way, the aiida virtual environment was created by conda in Ubuntu 17.10. Previously I used aiida v0.11.1 and some earlier versions. It seems that some implementation related to the database in the latest versions of aiida was changed?  I googled this password authentication error, and also tried some potential solutions (e.g. https://stackoverflow.com/questions/7695962/postgresql-password-authentication-failed-for-user-postgres) to fix this error, however, I didn't find one that work for me. In addition, issue #1535 may be a little bit similar to my password authentication error. I don't know much about postgresql and django, if there was some wrong statements in my issue report, please help correct me.

**Comment by yw-fang** [comment]
Although I am still not understand why the database previously used by earlier versions of aiida_core couldn't be used for the newest aiida, as a workaround, I created a new profile and in that way 'verdi daemon start' could run again.
