### ISSUE TITLE
Computer testing connection error after executing computer setup and configure: v1.0.0a2

### ISSUE THREAD

**Issue by yw-fang** [aiidateam/aiida_core#1841]
Hi, I got the following computer connection error when using aiida-v1.0.0a2 in a fresh virtual environment. 
Is there anything changed for configuring the computer after immigrating to the 'verdi click'?
In addition, how to add the prepend text in the step of computer setup as the old versions of aiida?

> (aiida) ywfang@ywfang:$ verdi computer setup 
> Info: enter "?" for help
> Computer label: stern-test
> Hostname: XXXXXXX
> Description []: stern for test
> Enable the computer? [True]: True
> Transport plugin: ssh
> Scheduler plugin: sge
> Shebang line (first line of each script, starting with #!) [#!/bin/bash]: 
> work directory on the computer [/scratch/{username}/aiida/]: /home/{username}/aiidawork/
> mpirun command [mpirun -np {tot_num_mpiprocs}]: 
> Success: computer "stern-test" stored in DB.
> Info: pk: 2, uuid: 738c77e8-6249-4065-ba4f-40745f91d9fb
> Info: Note: before using it with AiiDA, configure it using the command
> Info:   verdi computer configure stern-test
> Info: (Note: machine_dependent transport parameters cannot be set via 
> Info: the command-line interface at the moment)
> (aiida) ywfang@ywfang:$ verdi computer configure ssh stern-test
> Info: enter "?" for help
> User name [ywfang]: 
> port Nr [22]: 
> Look for keys []: 
> Error:  is not a valid boolean
> Info: switch automatic key file discovery on / off
> Look for keys []: True
> SSH key file []: ~/.ssh/id_rsa
> Connection timeout in s [60]: 
> Allow ssh agent []: False
> SSH proxy command []: 
> Compress file transfers [True]: False
> GSS auth [False]: False
> GSS kex [False]: 
> GSS deleg_creds [False]: 
> GSS host [XXXXXXXX]: 
> Load system host keys [True]: True
> Key policy [RejectPolicy]: WarningPolicy
> Connection cooldown time (sec) [5]: 
> Info: Configuring computer stern-test for user test@gmail.com.
> Success: stern-test successfully configured for test@gmail.com
> (aiida) ywfang@ywfang:$ verdi computer test stern-test
> Testing computer 'stern-test' for user test@gmail.com...
> > Testing connection...
> Error: ** Error while trying to connect to the computer! Cannot    perform following tests, stopping.
> IndexError: list index out of range
> (use the --traceback option to see the full traceback)

**Comment by greschd** [comment]
What do you get when running ``verdi computer test --print-traceback stern-test``?

Note that the help text is wrong, the option is called ``print-traceback``, not ``traceback``.

**Comment by yw-fang** [comment]
Hi, @greschd ,  thank you very much for your reply. 

The following shows the details:

Testing computer 'stern-test' for user test@gmail.com...
> Testing connection...
Error: ** Error while trying to connect to the computer! Cannot    perform following tests, stopping.
** Full traceback:
   Traceback (most recent call last):
     File "/home/ywfang/FANG/debug-aiida/aiida_core/aiida/cmdline/commands/cmd_computer.py", line 535, in computer_test
       with trans:
     File "/home/ywfang/FANG/debug-aiida/aiida_core/aiida/transport/transport.py", line 75, in __enter__
       self.open()
     File "/home/ywfang/FANG/debug-aiida/aiida_core/aiida/transport/plugins/ssh.py", line 484, in open
       proxy = _DetachedProxyCommand(proxystring)
     File "/home/ywfang/FANG/debug-aiida/aiida_core/aiida/transport/util.py", line 39, in __init__
       super(_DetachedProxyCommand, self).__init__(command_line)
     File "/home/ywfang/miniconda3/envs/aiida/lib/python2.7/site-packages/paramiko/proxy.py", line 55, in __init__
       bufsize=0)
     File "/home/ywfang/miniconda3/envs/aiida/lib/python2.7/subprocess.py", line 394, in __init__
       errread, errwrite)
     File "/home/ywfang/miniconda3/envs/aiida/lib/python2.7/subprocess.py", line 919, in _execute_child
       executable = args[0]
   IndexError: list index out of range

**Comment by chrisjsewell** [comment]
I have exactly the same issue after upgrading from v0.12

```python
   Traceback (most recent call last):
     File "/Users/cjs14/GitHub/aiida_core/aiida/cmdline/commands/cmd_computer.py", line 521, in computer_test
       with trans:
     File "/Users/cjs14/GitHub/aiida_core/aiida/transport/transport.py", line 80, in __enter__
       self.open()
     File "/Users/cjs14/GitHub/aiida_core/aiida/transport/plugins/ssh.py", line 484, in open
       proxy = _DetachedProxyCommand(proxystring)
     File "/Users/cjs14/GitHub/aiida_core/aiida/transport/util.py", line 40, in __init__
       super(_DetachedProxyCommand, self).__init__(command_line)
     File "//anaconda/envs/aiida/lib/python2.7/site-packages/paramiko/proxy.py", line 55, in __init__
       bufsize=0)
     File "//anaconda/envs/aiida/lib/python2.7/subprocess.py", line 394, in __init__
       errread, errwrite)
     File "//anaconda/envs/aiida/lib/python2.7/subprocess.py", line 919, in _execute_child
       executable = args[0]
   IndexError: list index out of range

```

Breaking on `proxy = _DetachedProxyCommand(proxystring)`, the `proxystring` is empty (="")

Additionally, in `verdi computer configure ssh`, there are now no defaults set for:

```
Look for keys []:
SSH key file []:
Allow ssh agent []:
```

So you have to enter an SSH key file

**Comment by chrisjsewell** [comment]
and I assume its related that:

```
verdi calculation logshow 255
*** 255 [Test QE cx1]: SUBMISSIONFAILED
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 5 LOG MESSAGES:
+-> WARNING at 2018-08-17 13:13:04.702463+00:00
 | iteration 1 of do_submit excepted, retrying after 1 seconds
 | Traceback (most recent call last):
 |   File "/Users/cjs14/GitHub/aiida_core/aiida/work/utils.py", line 121, in exponential_backoff_retry
 |     result = yield coro()
 |   File "//anaconda/envs/aiida/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "//anaconda/envs/aiida/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "//anaconda/envs/aiida/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/Users/cjs14/GitHub/aiida_core/aiida/work/job_processes.py", line 68, in do_submit
 |     transport = yield request
 |   File "//anaconda/envs/aiida/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "//anaconda/envs/aiida/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 3, in raise_exc_info
 | IndexError: list index out of range

```

**Comment by chrisjsewell** [comment]
So an apparent bug is that, because in `verdi computer configure ssh` the `SSH proxy command` no longer defaults to None, even if you don't enter anything, it sets the `'proxy_command'=''`. So when the line `proxystring = connection_arguments.pop('proxy_command', None)` is called [here](https://github.com/aiidateam/aiida_core/blob/d6cb52f40d0b5382a27b8ec640feaf2389002b38/aiida/transport/plugins/ssh.py#L482), it returns '' instead of None.

**Comment by greschd** [comment]
Adding @DropD and @sphuber since it seems to be related to the command line interface.

**Comment by chrisjsewell** [comment]
See #1893 for the fix

**Comment by DropD** [comment]
The `NoneParameter` in #1893 could be a starting point for a fix, however as is it disables `proxy_command` completely.
