### ISSUE TITLE
`verdi computer configure ssh` broken

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida_core#1893]
Basically the migration to click (cd42a5d65060629357e8c206c6536bb3ea75027d) has introduced a bug which has made it impossible to run any computations (if not using a proxy-command).

As I mention in #1841, before this update these keys in [SshTransport](https://github.com/aiidateam/aiida_core/blob/d6cb52f40d0b5382a27b8ec640feaf2389002b38/aiida/transport/plugins/ssh.py) were optional: 'look_for_keys', 'key_filename', 'proxy_command' and 'allow_agent', and I think if you left them blank they were omitted from the saved data. Now they are mandatory, even if not being used. Furthermore, if left blank the 'SSH key file' option will throw an error;

```
SSH key file []:
Error: Path '' does not exist.
Info: Manually pass a key file
```

and the 'proxy_command' will be set as '' not None (as required).

Fixes:

1. All `def _convert` methods should be removed, since they are no longer actually called.
2. Changes to the `_valid_connect_options` list need to be made, such as the types of `key_filename` and `proxy_command`.

If I create this class:

```python
class NoneParamType(StringParamType):
    """
    Parameter which is converted to None
    """
    name = 'none'

    def convert(self, value, param, ctx):
        return None

    def __repr__(self):
        return 'NONE'
```

and change the line:

```python
...
        ('proxy_command', {'type': NoneParamType(), 'prompt': 'SSH proxy command', 'help': 'SSH proxy command', 'non_interactive_default': True}), 
...
```

This *fixes* `computer configure test`. However, when I try to run a computation, I still an error which I suspect is linked to this issue (it worked with v0.12):

```python
*** 272 [Test QE cx1]: SUBMISSIONFAILED
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 5 LOG MESSAGES:
+-> WARNING at 2018-08-17 16:43:35.156359+00:00
 | iteration 1 of do_submit excepted, retrying after 1 seconds
 | Traceback (most recent call last):
 |   File "/Users/cjs14/GitHub/aiida_core/aiida/work/utils.py", line 121, in exponential_backoff_retry
 |     result = yield coro()
 |   File "//anaconda/envs/aiida/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "//anaconda/envs/aiida/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "//anaconda/envs/aiida/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/Users/cjs14/GitHub/aiida_core/aiida/work/job_processes.py", line 68, in do_submit
 |     transport = yield request
 |   File "//anaconda/envs/aiida/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "//anaconda/envs/aiida/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 3, in raise_exc_info
 | OSError: [Errno 2] No such file or directory
...
```

Any help pinpointing the source of this error would be greatly appreciated, since the traceback doen't give much to go off!

**Comment by chrisjsewell** [comment]
Fixed the computation after `reentry scan ` and restarting the daemon

**Comment by sphuber** [comment]
@chrisjsewell I think there should be a second stack trace after the one you printed that should give us more information about what actually caused the exception in `do_submit`. The current stacktrace is just how the exception was set on the future. Could you still retrieve more of the daemon log from that calculation?

**Comment by chrisjsewell** [comment]
@sphuber as I mention, the `do_submit` error was fixed once I'd had restarted the daemon (and performed a `reentry scan`), after making the code changes. It was most definitely a result of `proxy_command` being to `""` instead of `None`.

The main changes I suggest making are, in `aiida_core/aiida/cmdline/params/types/`, create a an `emptystring.py` (similar to `nonemptystring.py`):

```python
"""
Module for the non empty string parameter type
"""

from click.types import StringParamType


class EmptyStringParamType(StringParamType):
    """
    Parameter that, if an empty string, is set to None
    """
    name = 'emptystring'

    def convert(self, value, param, ctx):
        newval = super(NonemptyStringParamType, self).convert(value, param, ctx)
        if not newval:  # None or empty string
            newval = None

        return newval

    def __repr__(self):
        return 'EMPTYSTRING'
```

and update or create a new `AbsolutePathParamType`, such that, if the path is `""`, it return None (without checking if the path exists)

**Comment by chrisjsewell** [comment]
@dev-zero well yes, but how do you specifically parse `None` on the command line interface, and not the empty `str`?

**Comment by dev-zero** [comment]
One side I think we need the extend the `create_option` and the spec to allow for optional (and dependent) attributes when doing the configuration interactively. Everything else will backfire at some point (assume the case where an attribute could be None, an empty string or a non-empty string).

On the other side, we have to make our parameter handling in the classes more robust: Instead of `if proxystring is not None:` just use `if proxystring:`.

In general: do we really gain so much from this overly abstract `connect_options` facility? Wouldn't it be much easier to write a normal click function instead per transport plugin and manually script out the interactive part? For example: why am I being asked at all about the path for the SSH key files if I answered the 'Look for keys' with 'n'? The same goes for the kerberos/GSS stuff.
