### ISSUE TITLE
tab completion cmdline prints error message in new environment

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#1906]
In a completely fresh AiiDA environment the tab completion command line
```
eval "$(_VERDI_COMPLETE=source-bash verdi)"
```
leads to the following error message, which is misleading since nothing went wrong. Tab completion actually works afterwards, and there shouldn't have to be a profile before setting up AiiDA.

```
Traceback (most recent call last):
  File "/home/hauselmann/miniconda2/envs/aiida-test-aipro-conda/bin/verdi", line 9, in <module>
    sys.exit(verdi())
  File "/home/hauselmann/miniconda2/envs/aiida-test-aipro-conda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/hauselmann/miniconda2/envs/aiida-test-aipro-conda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/hauselmann/miniconda2/envs/aiida-test-aipro-conda/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hauselmann/miniconda2/envs/aiida-test-aipro-conda/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hauselmann/miniconda2/envs/aiida-test-aipro-conda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hauselmann/miniconda2/envs/aiida-test-aipro-conda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hauselmann/Projects/test-aipro/test-aipro-conda/aiida_core/aiida/cmdline/utils/decorators.py", line 60, in decorated_function
    load_dbenv_if_not_loaded(*load_dbenv_args, **load_dbenv_kwargs)
  File "/home/hauselmann/Projects/test-aipro/test-aipro-conda/aiida_core/aiida/cmdline/utils/decorators.py", line 39, in load_dbenv_if_not_loaded
    load_dbenv(**kwargs)
  File "/home/hauselmann/Projects/test-aipro/test-aipro-conda/aiida_core/aiida/backends/utils.py", line 64, in load_dbenv
    load_profile(profile=profile)
  File "/home/hauselmann/Projects/test-aipro/test-aipro-conda/aiida_core/aiida/backends/profile.py", line 40, in load_profile
    config = get_profile_config(settings.AIIDADB_PROFILE)
  File "/home/hauselmann/Projects/test-aipro/test-aipro-conda/aiida_core/aiida/common/setup.py", line 338, in get_profile_config
    profile, ', '.join(get_profiles_list())))
aiida.common.exceptions.ProfileConfigurationError: No profile configuration found for None, allowed values are: .
```

**Comment by DropD** [comment]
It was actually `verdi daemon start` which threw the exception
