### ISSUE TITLE
Pytest fails before running tests

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#1911]
## Travis output (everything prior has passed)
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config.py", line 52, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config.py", line 163, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config.py", line 941, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config.py", line 1091, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config.py", line 1053, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 145, in find_module
    _write_pyc(state, co, source_stat, pyc)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 269, in _write_pyc
    marshal.dump(co, fp.file)
AttributeError: '_io.BufferedWriter' object has no attribute 'file'
```

## Suggested fix:

Let's stick with only one testing framework?

**Comment by DropD** [comment]
Why does pytest even run?

**Comment by DropD** [comment]
This is actually interesting... I have never before seen Python fail while writing a `.pyc` file!

**Comment by chrisjsewell** [comment]
> Why does pytest even run?

This output is actually from my plugin repo (https://travis-ci.org/chrisjsewell/aiida-crystal17/jobs/421127367). I would strongly suggest supporting `pytest` since (in my opinion) it has many benefits over `unittest` and is a lot easier to use for plugin development. 

It works fine for v0.12.1, so I have no idea whats broken it in v1!?

**Comment by chrisjsewell** [comment]
Thanks @dev-zero, I can confirm that if I add `pip install -U pytest==3.6.3`, after the aiida install, everything works fine
