### ISSUE TITLE
flawed logic in `aiida.orm.implementation.general.node:AbstractNode._iter_all_same_nodes` if hash_ is not valid

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#1914]
While working on getting the tests running on Python 3, I encountered an interesting error after a broken change to the hashing implementation:

```
Traceback (most recent call last):
  File "/home/travis/build/dev-zero/aiida_core/aiida/backends/tests/nodes.py", line 122, in test_simple_unequal_nodes
    n2.store(use_cache=True)
  File "/home/travis/build/dev-zero/aiida_core/aiida/orm/implementation/general/node.py", line 1678, in store
    same_node = self._get_same_node() if use_cache else None
  File "/home/travis/build/dev-zero/aiida_core/aiida/orm/implementation/general/node.py", line 1819, in _get_same_node
    return next(self._iter_all_same_nodes())
  File "/home/travis/build/dev-zero/aiida_core/aiida/orm/implementation/general/node.py", line 1845, in _iter_all_same_nodes
    return (n for n in same_nodes if n._is_valid_cache())
UnboundLocalError: local variable 'same_nodes' referenced before assignment
```

in fact, looking at the implementation it seems that the logic here is a bit flawed:

```python
    def _iter_all_same_nodes(self):
        """
        Returns an iterator of all same nodes.
        """
        if not self._cacheable:
            return iter(())

        from aiida.orm.querybuilder import QueryBuilder

        hash_ = self.get_hash()
        if hash_:
            qb = QueryBuilder()
            qb.append(self.__class__, filters={'extras._aiida_hash': hash_}, project='*', subclassing=False)
            same_nodes = (n[0] for n in qb.iterall())
        return (n for n in same_nodes if n._is_valid_cache())
```

if `hash_` is not valid, `same_nodes` is never set, but then used in the `return`.

Anyone an idea what was the intention here?

**Comment by greschd** [comment]
Yeah, it should probably just return an empty iterator in that case. I'd guess this was never caught because caching is interrupted at a higher level when the hash is not valid.

**Comment by dev-zero** [comment]
so, something like the following?

```python
    def _iter_all_same_nodes(self):
        """
        Returns an iterator of all same nodes.
        """
        if not self._cacheable:
            return iter(())

        hash_ = self.get_hash()
        if not hash_:
            return iter(())

        from aiida.orm.querybuilder import QueryBuilder
        qb = QueryBuilder()
        qb.append(self.__class__, filters={'extras._aiida_hash': hash_}, project='*', subclassing=False)
        return (n[0] for n in qb.iterall() if n[0]._is_valid_cache())
```
