### ISSUE TITLE
"OSError: [Errno 24] Too many open files"

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida_core#1923]
After the daemon has been running for a few hours, sometimes all transport tasks will begin to fail with the following error in the daemon log:
```
08/30/2018 11:53:11 PM <12517> aiida.work.transports: [DEBUG] Transport request opening transport for AuthInfo for marco.borelli@epfl.ch on daint5
08/30/2018 11:53:11 PM <12517> aiida.work.transports: [ERROR] exception occurred while trying to open transport:
 [Errno 24] Too many open files
08/30/2018 11:53:11 PM <12517> aiida.work.transports: [ERROR] Exception whilst using transport:
Traceback (most recent call last):
  File "/home/mborelli/repos/aiida_dev/aiida-core/aiida/work/transports.py", line 101, in request_transport
    yield transport_request.future
  File "/home/mborelli/repos/aiida_dev/aiida-core/aiida/work/job_processes.py", line 128, in do_update
    transport = yield request
  File "/home/mborelli/venvs/aiida_dev/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/mborelli/venvs/aiida_dev/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
OSError: [Errno 24] Too many open files
```

I used `lsof` to count the open file handles per process, and summed those with the same process name. Here are those with more than 100 files:
```
ssh 10389
python2 3942
verdi 1374
aux 340
jupyter-n 243
gdbus 232
kworker/1 112
```

In particular, there are 335 `ssh` processes with 31/32 files each. By contrast, there are only 5 `python2` and 2 `verdi` processes.
A similar issue was reported here, but then closed: https://github.com/aiidateam/aiida_core/issues/1010

**Comment by sphuber** [comment]
Issue #1010 is not relevant in this case because that was due to the usage of pickle files for checkpointing processes, which is now stored in the database.

**Comment by dev-zero** [comment]
Looks like we are leaking file handles on one side and do not properly close SSH connections on the other side. For the first one you may try 9760ffa22309b792143409556a3759d5e4b3a7f0 which fixes at least one definitive file handle leak. Some others are hidden inside the `pgtest` library we are using (shown on Python 3).
