### ISSUE TITLE
TransportQueue not working on Python 3

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#1930]
Running the tests for the TransportQueue for Python 3 on Travis yields the following errors:

```
======================================================================
ERROR: test_get_transport_interleaved (aiida.backends.tests.work.test_transport.TestTransportQueue)
Test interleaved calls to get the same transport
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dev-zero/aiida_core/aiida/backends/tests/work/test_transport.py", line 69, in test_get_transport_interleaved
    loop.run_sync(lambda: [interleaved(self.authinfo), interleaved(self.authinfo)])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tornado/ioloop.py", line 456, in run_sync
    if not future_cell[0].done():
AttributeError: 'NoneType' object has no attribute 'done'
======================================================================
ERROR: test_get_transport_nested (aiida.backends.tests.work.test_transport.TestTransportQueue)
Test nesting calls to get the same transport
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dev-zero/aiida_core/aiida/backends/tests/work/test_transport.py", line 57, in test_get_transport_nested
    loop.run_sync(lambda: nested(transport_queue, self.authinfo))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tornado/ioloop.py", line 457, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
tornado.ioloop.TimeoutError: Operation timed out after None seconds
[...]
```

If I understood it correctly, it seems like we are putting a Future in the queue which is actually a `None`. It is likely that this is a broken error code path like in #1914 and the actual problem is a different one which gets masked.

@muhrin any ideas?

**Comment by giovannipizzi** [comment]
Note that there are some disabled tests that need to be reenabled.

**Comment by muhrin** [comment]
Thanks.  Let me have a look...
