### ISSUE TITLE
GAIerror in JobCalculation TransportTask

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1934]
Observed relatively frequently on recent version of `develop` on workstation of @sohier .

```
09/03/2018 04:08:55 PM <18675> aiida.aiida_quantumespresso_epc.calculations.epc.EPCCalculation: [WARNING] iteration 3 of do_update excepted
, retrying after 80 seconds
09/03/2018 04:10:15 PM <18675> aiida.work.transports: [ERROR] Exception whilst using transport:
Traceback (most recent call last):
  File "/home/sohier/Codes/aiida_core/aiida/work/transports.py", line 101, in request_transport
    yield transport_request.future
  File "/home/sohier/Codes/aiida_core/aiida/work/job_processes.py", line 128, in do_update
    transport = yield request
  File "/home/sohier/aiidapy/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/sohier/aiidapy/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
gaierror: [Errno -2] Name or service not known
```

**Comment by dev-zero** [comment]
This error usually indicates a network error (DNS resolution failed or similar), could you setup some simple monitoring on or against that machine and verify that this is not the issue?
But it would nevertheless be nice to have more information about the actual address it failed to resolve here.

**Comment by sphuber** [comment]
Verified with original report that this no longer occurs so it probably was a local setup misconfiguration or temporary problem. Closing
