### ISSUE TITLE
Change of behaviour of verdi setup

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#1953]
I am using the current develop version of AiiDA (commit 2ad1c4a) and verdi setup doesn't work as it used to (maybe because of the click related changes?). 

More specifically, when things get bad with a database for any reason and I want to start from scratch, I delete the database corresponding to the profile that interests me, I recreate it and then I used to run `verdi -p my_profile install/setup` to initialise it.

The last command was initializing the DB based on the profile's information (stored in .aiida/config.json). However now I see that I have to provide again the information to initialize the DB

E.g. 

```
        "test_dj1": {
            "AIIDADB_ENGINE": "postgresql_psycopg2",
            "AIIDADB_PASS": "12345678",
            "AIIDADB_NAME": "test_aiidadb_dj1",
            "AIIDADB_HOST": "localhost",
            "AIIDADB_BACKEND": "django",
            "AIIDADB_PORT": "5432",
            "PROFILE_UUID": "12345678",
            "default_user_email": "aiida@localhost",
            "AIIDADB_REPOSITORY_URI": "file:///home/szoupanos/.aiida/repository-test_dj1/",
            "AIIDADB_USER": "aiida"
        },
```

Is there any way to reuse an existing profile's info to initialiaze the corresponding DB?

**Comment by szoupanos** [comment]
This doesn't seem to work

```
(aiidapy) szoupanos@theospc38:~/aiida-code/aiida_core$ verdi -p test_dj1 calculation list
Traceback (most recent call last):
  File "/home/szoupanos/aiidapy/bin/verdi", line 9, in <module>
    sys.exit(verdi())
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/szoupanos/aiida-code/aiida_core/aiida/cmdline/utils/decorators.py", line 64, in decorated_function
    return function(*args, **kwargs)
  File "/home/szoupanos/aiida-code/aiida_core/aiida/cmdline/commands/cmd_calculation.py", line 127, in calculation_list
    raw=raw,
  File "/home/szoupanos/aiida-code/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 1038, in _list_calculations
    user_id = backend.users.get_automatic_user().id
  File "/home/szoupanos/aiida-code/aiida_core/aiida/orm/user.py", line 114, in get_automatic_user
    return self.get(email)
  File "/home/szoupanos/aiida-code/aiida_core/aiida/orm/user.py", line 81, in get
    results = self.find(email=email)
  File "/home/szoupanos/aiida-code/aiida_core/aiida/orm/implementation/django/user.py", line 55, in find
    for dbuser in dbusers:
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/szoupanos/aiidapy/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "db_dbuser" does not exist
LINE 1: ...user"."is_active", "db_dbuser"."date_joined" FROM "db_dbuser...
```

However, I was mistaken. After providing an email address, first name & last name, then it used the info at config.json to connect to the right DB and initialize it

**Comment by szoupanos** [comment]
So, it seems that everything is there, just 1-2 steps furher.

**Comment by szoupanos** [comment]
Thanks Seb!
