### ISSUE TITLE
Import of archive excepts if it does not contain any nodes

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2022]
An archive file without any nodes will result in the following exception when imported:
```
Traceback (most recent call last):
  File "/home/sphuber/code/aiida/env/dev/aiida-core/aiida/backends/tests/export_and_import.py", line 751, in test_group_export
    import_data(filename1, silent=True)
  File "/home/sphuber/code/aiida/env/dev/aiida-core/aiida/orm/importexport.py", line 323, in import_data
    silent=silent)
  File "/home/sphuber/code/aiida/env/dev/aiida-core/aiida/orm/importexport.py", line 433, in import_data_dj
    import_nodes_uuid = set(v['uuid'] for v in data['export_data'][NODE_ENTITY_NAME].values())
KeyError: 'Node'
```

**Comment by sphuber** [comment]
Fixed in PR #2024
