### ISSUE TITLE
add unicode_literal from future to all files

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2040]
To check if this breaks python2 code

**Comment by giovannipizzi** [comment]
Apparently, this is not a good idea.
I did this, and I started getting a huge amount of these warnings:
```
Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
```

Moreover, the code started crashing, e.g. with 
```
Traceback (most recent call last):
  File "/Users/pizzi/.virtualenvs/aiida_core_dev/bin/verdi", line 9, in <module>
    sys.exit(verdi())
  File "/Users/pizzi/.virtualenvs/aiida_core_dev/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pizzi/.virtualenvs/aiida_core_dev/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/pizzi/.virtualenvs/aiida_core_dev/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pizzi/.virtualenvs/aiida_core_dev/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pizzi/.virtualenvs/aiida_core_dev/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/pizzi/git/aiida_core/aiida/cmdline/utils/decorators.py", line 71, in decorated_function
    return function(*args, **kwargs)
  File "/Users/pizzi/git/aiida_core/aiida/cmdline/commands/cmd_shell.py", line 46, in shell
    run_shell(interface=interface)
  File "/Users/pizzi/git/aiida_core/aiida/cmdline/utils/shell.py", line 70, in run_shell
    curr_shell()
  File "/Users/pizzi/git/aiida_core/aiida/cmdline/utils/shell.py", line 36, in ipython
    ipy_version()
  File "/Users/pizzi/git/aiida_core/aiida/cmdline/utils/shell.py", line 131, in _ipython
    user_ns = get_start_namespace()
  File "/Users/pizzi/git/aiida_core/aiida/cmdline/utils/shell.py", line 84, in get_start_namespace
    user_ns[alias] = getattr(__import__(app_mod, {}, {}, model_name), model_name)
  File "/Users/pizzi/git/aiida_core/aiida/orm/__init__.py", line 15, in <module>
    from aiida.orm.calculation import *
TypeError: Item in ``from list'' not a string
```
Apparently this has struck other project and they solved by removing the `from __future__ import unicode_literal`, see e.g. https://github.com/sigmavirus24/twine/commit/c2cd72d0f4ff4d380845333fbfaaf2c92d6a5674
