### ISSUE TITLE
Randomly failing test, to improve

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2133]
https://travis-ci.org/aiidateam/aiida_core/jobs/446630031

```
======================================================================
ERROR: test_load_node (aiida.backends.tests.orm.utils.loaders.TestOrmUtils)
Test the functionality of load_node.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aiidateam/aiida_core/aiida/backends/tests/orm/utils/loaders.py", line 199, in test_load_node
    loaded_node = load_node(uuid=node.uuid[:2])
  File "/home/travis/build/aiidateam/aiida_core/aiida/orm/utils/__init__.py", line 174, in load_node
    return load_entity(NodeEntityLoader, identifier=identifier, pk=pk, uuid=uuid, label=label, sub_classes=sub_classes, query_with_dashes=query_with_dashes)
  File "/home/travis/build/aiidateam/aiida_core/aiida/orm/utils/__init__.py", line 80, in load_entity
    return entity_loader.load_entity(identifier, identifier_type, sub_classes=sub_classes, query_with_dashes=query_with_dashes)
  File "/home/travis/build/aiidateam/aiida_core/aiida/orm/utils/loaders.py", line 196, in load_entity
    raise MultipleObjectsError(error)
MultipleObjectsError: multiple Node entries found with UUID<c9>
----------------------------------------------------------------------
```
Probably two nodes generated by chance with the same starting UUID? Can we improve the test to avoid this random failures?

**Comment by sphuber** [comment]
I am not sure how we can completely avoid the possibility while keeping the test, but we can make the chances almost negligible by taking the first 8 characters instead of just two
