### ISSUE TITLE
Deepcopy fails in pika

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#2146]
Fresh Aiida installation from yesterday. Develop branch. Python 2.7.15. Verdi setup looks okey. Tests without a test profile pass. I get this when running a test workchain (and also the same for the django tests when enabling the test profile):

```
Traceback (most recent call last):
  File "sometest.py", line 67, in <module>
    main()
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/efl/src/aiida-vasp/examples/auxiliary.py", line 17, in decorated_cmd_fn
    return cmd_function(*args, **kwargs)
  File "run_vasp_lean.py", line 63, in main
    run(workchain, **inputs)
  File "/home/efl/src/aiida_core/aiida/work/launch.py", line 45, in run
    runner = runners.get_runner()
  File "/home/efl/src/aiida_core/aiida/work/runners.py", line 59, in get_runner
    RUNNER = new_runner()
  File "/home/efl/src/aiida_core/aiida/work/runners.py", line 48, in new_runner
    return Runner(**kwargs)
  File "/home/efl/src/aiida_core/aiida/work/runners.py", line 99, in __init__
    self._setup_rmq(**rmq_config)
  File "/home/efl/src/aiida_core/aiida/work/runners.py", line 356, in _setup_rmq
    self._communicator.connect()
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/kiwipy/rmq/communicator.py", line 294, in connect
    self._loop.run_sync(self._message_subscriber.connect)
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/tornado/ioloop.py", line 453, in run_sync
    self.start()
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/kiwipy/rmq/communicator.py", line 103, in connect
    channel = yield connector.open_channel()
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/kiwipy/rmq/pubsub.py", line 111, in open_channel
    connection_future = self.connect()
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/kiwipy/rmq/pubsub.py", line 94, in connect
    custom_ioloop=self._loop)
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/pika/adapters/tornado_connection.py", line 55, in __init__
    stop_ioloop_on_close)
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 73, in __init__
    on_open_error_callback, on_close_callback)
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/pika/connection.py", line 1081, in __init__
    self.params = (copy.deepcopy(parameters) if parameters is not None else
  File "/usr/local/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/home/efl/env/aiidadevel/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
  File "/usr/local/lib/python2.7/bdb.py", line 53, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/local/lib/python2.7/bdb.py", line 88, in dispatch_return
    self.user_return(frame, arg)
  File "/usr/local/lib/python2.7/pdb.py", line 190, in user_return
    self.interaction(frame, None)
  File "/usr/local/lib/python2.7/pdb.py", line 209, in interaction
    self.print_stack_entry(self.stack[self.curindex])
  File "/usr/local/lib/python2.7/pdb.py", line 900, in print_stack_entry
    prompt_prefix)
  File "/usr/local/lib/python2.7/bdb.py", line 381, in format_stack_entry
    s = s + repr.repr(rv)
  File "/usr/local/lib/python2.7/repr.py", line 24, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/local/lib/python2.7/repr.py", line 34, in repr1
    s = __builtin__.repr(x)
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/pika/connection.py", line 186, in __repr__
    (self.__class__.__name__, self.host, self.port,
  File "/home/efl/env/aiidadevel/lib/python2.7/site-packages/pika/connection.py", line 393, in host
    return self._host
AttributeError: _host
```

A hint using pdb:

```
> /home/efl/env/aiidadevel/lib/python2.7/site-packages/pika/connection.py(1081)__init__()
-> self.params = (copy.deepcopy(parameters) if parameters is not None else
(Pdb) print parameters
<URLParameters host=127.0.0.1 port=5672 virtual_host=/ ssl=False>
(Pdb) s
--Call--
> /usr/local/lib/python2.7/copy.py(145)deepcopy()
-> def deepcopy(x, memo=None, _nil=[]):
```

etc...

```
> /home/efl/env/aiidadevel/lib/python2.7/copy_reg.py(144)_slotnames()
-> return names
(Pdb) 
--Return--
```

And then the trace shown above is thrown. The result is that `verdi devel tests` just hangs and the same for the workchain test. Seems to me that this should not happen.

**Comment by sphuber** [comment]
@espenfl is this still relevant for the beta release?

**Comment by espenfl** [comment]
I have not yet managed to reproduce this on the beta so let us close it. I will open it again if I see it.
