### ISSUE TITLE
self._backend_entity.get_metadata() should self._backend_entity.be _get_metadata() in AuthInfo class

### ISSUE THREAD

**Issue by PhilippRue** [aiidateam/aiida_core#2221]
When running `verdi computer test` the tests fail because `get_metadata` of the `AuthInfo` class in `aiida/orm/authinfos.py` was changed to `_get_metadata`.

**Comment by muhrin** [comment]
Thanks Philipp,

this may have been fixed on our current working branch, `provenance_redesign` but to find out could you provide more details?  Currently (at least for a local computer) test work for me.  What is your failure mode?

**Comment by PhilippRue** [comment]
Hi Martin,

if I use the `develop` branch (commit 60bc39862) I get this for a local computer:

```
% verdi computer test my_mac --print-traceback
Testing computer 'my_mac' for user p.ruessmann@fz-juelich.de...
> Testing connection...
> Checking that no spurious output is present...
      [OK]
> Getting job list...
  `-> OK, 5 jobs found in the queue.
> Creating a temporary file in the work directory...
  `-> Getting the remote user name...
      [remote username: ***]
Error: * The test raised an exception!
** Full traceback:
   Traceback (most recent call last):
     File ".../aiida_core/aiida/cmdline/commands/cmd_computer.py", line 561, in computer_test
       succeeded = test(transport=trans, scheduler=sched, authinfo=authinfo)
     File ".../aiida_core/aiida/cmdline/commands/cmd_computer.py", line 145, in _computer_create_temp_file
       workdir = authinfo.get_workdir().format(username=remote_user)
     File ".../aiida_core/aiida/orm/authinfos.py", line 136, in get_workdir
       metadata = self.get_metadata()
     File ".../aiida_core/aiida/orm/authinfos.py", line 122, in get_metadata
       return self._backend_entity.get_metadata()
   AttributeError: 'DjangoAuthInfo' object has no attribute 'get_metadata'
Some tests failed! (1 out of 4 failed)
```

This is then fixed by renaming `get_metadata ` to `_ get_metadata` in `aiida/orm/authinfos.py`
