### ISSUE TITLE
`verdi calculation gotocomputer` not working

### ISSUE THREAD

**Issue by PhilippRue** [aiidateam/aiida_core#2234]
When trying to go to the working directory of a calculation via `verdi calculation gotocomputer` it does not work:
```
$ verdi calculation gotocomputer 141

Traceback (most recent call last):
  File ".../aiida/virtenv_aiida_1.0/bin/verdi", line 9, in <module>
    sys.exit(verdi())
  File ".../aiida/virtenv_aiida_1.0/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File ".../aiida/virtenv_aiida_1.0/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File ".../aiida/virtenv_aiida_1.0/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../aiida/virtenv_aiida_1.0/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../aiida/virtenv_aiida_1.0/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../aiida/virtenv_aiida_1.0/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File ".../aiida/aiida_core/aiida/cmdline/commands/cmd_calculation.py", line 48, in calculation_gotocomputer
    transport = calculation._get_transport()
  File ".../aiida/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 1660, in _get_transport
    return self._get_authinfo().get_transport()
AttributeError: 'DjangoAuthInfo' object has no attribute 'get_transport'
```

The computer where the calculation ran is a remote one with the torque scheduler (see part of `verdi comuter show` output):
```
 * Enabled:        True
 * Transport type: ssh
 * Scheduler type: torque
```

I use the current `develop` branch.

**Comment by sphuber** [comment]
Thanks for the report @PhilippRue . We are in the middle of a big ORM refactor and as you have noticed, the tests do not cover everything and some things are broken in `develop`. I have put out a fix for this bug in PR #2235.
