### ISSUE TITLE
REST API has unhandled errors

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2249]
This was identified by analyzing errors in apache logs on Materials cloud:

```
mod_wsgi (pid=13355): Exception occurred processing WSGI script '/home/ubuntu/backend-explore/wsgifiles/twodmaterials.wsgi'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/home/ubuntu/aiida_core/aiida/restapi/api.py", line 353, in handle_error
    raise e
RestValidationError: either no object's id starts with '28de-d209-4580-b281-43c0abacf0a4' or the corresponding object is not of type aiida.orm.node.Node
```

```
mod_wsgi (pid=13355): Exception occurred processing WSGI script '/home/ubuntu/backend-explore/wsgifiles/twodmaterials.wsgi'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/home/ubuntu/aiida_core/aiida/restapi/api.py", line 353, in handle_error
    raise e
RestValidationError: More than one node found. Provide longer starting pattern for id.
```

```
mod_wsgi (pid=13355): Exception occurred processing WSGI script '/home/ubuntu/backend-explore/wsgifiles/twodmaterials.wsgi'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/home/ubuntu/aiida_core/aiida/restapi/api.py", line 353, in handle_error
    raise e
RestValidationError: either no object's id starts with '00000' or the corresponding object is not of type aiida.orm.node.Node
```

```
mod_wsgi (pid=13355): Exception occurred processing WSGI script '/home/ubuntu/backend-explore/wsgifiles/twodmaterials.wsgi'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/home/ubuntu/aiida_core/aiida/restapi/api.py", line 353, in handle_error
    raise e
TypeError: 'NoneType' object is not iterable
```

**Comment by ltalirz** [comment]
analysis by @giovannipizzi 

1. `handle_error` is not catching properly some exceptions and just raising, so I imagine the user would see a 500 error (even if this is masked because it happens in the rest API via Ajax). 
Some (like the TypeError) probably are other problems and need to be fixed; others (like `either no object's id starts with '00000' or the corresponding object is not of type aiida.orm.node.Node`) should be instead returned as a message to the user in the `if` statement a few lines above `File "/home/ubuntu/aiida_core/aiida/restapi/api.py", line 353`:
https://github.com/aiidateam/aiida_core/blob/6830fa2f47ae952f9bda0ee508c7a653fc57d735/aiida/restapi/api.py#L338

2. I think the the `if` statement a few lines above `File "/home/ubuntu/aiida_core/aiida/restapi/api.py", line 353` would return always a 200 error, while we should return a different error code (e.g. a 404 if no node is found, like the `'00000'` error above, and probably also when more than a node is found. 
I think this can be achieved by passing the error code as a second parameter in this line https://github.com/aiidateam/aiida_core/blob/6830fa2f47ae952f9bda0ee508c7a653fc57d735/aiida/restapi/api.py#L350
i.e. `return jsonify(response), 404` as e.g. shown here (but I didn't check it): https://stackoverflow.com/a/13793320

3. checking the error code would be a good thing to add to the tests of the rest api
