### ISSUE TITLE
AiiDA installation fails: No package 'gss' found

### ISSUE THREAD

**Issue by asle85** [aiidateam/aiida_core#2286]
When installing AiiDA (python 2.7 on Ubuntu 16.04), I get the following error:

```
Collecting python-gssapi
  Using cached https://files.pythonhosted.org/packages/a4/9e/648b4e85235097edcee561c986f7075cb1606be24c514cfcdd2930e35c5e/python-gssapi-0.6.4.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no previously-included files found matching 'setup.pyc'
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    pycparser.ply.lex: module references __file__
    pycparser.ply.lex: module MAY be using inspect.getsourcefile
    pycparser.ply.yacc: module references __file__
    pycparser.ply.yacc: module MAY be using inspect.getsourcefile
    pycparser.ply.yacc: module MAY be using inspect.stack
    pycparser.ply.ygen: module references __file__
    
    Installed /tmp/pip-install-fvZhmV/python-gssapi/.eggs/pycparser-2.19-py2.7.egg
    running egg_info
    creating pip-egg-info/python_gssapi.egg-info
    writing requirements to pip-egg-info/python_gssapi.egg-info/requires.txt
    writing pip-egg-info/python_gssapi.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/python_gssapi.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/python_gssapi.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/python_gssapi.egg-info/SOURCES.txt'
    Package gss was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gss.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'gss' found
    gssapi/bindings/__pycache__/_cffi__x98b1bd10x6c820412.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x1409c8d6xa79bfeef.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x48e8d08bxdba4f2a1.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x77145060x5d98e1c3.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xfd2d2f42x2a0d7c22.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x4a7630a9xa883e720.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xb1ec24cfxdc4bc63b.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x9bd034dcxc4f5555d.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xd6880fbfx39d25428.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xdd2c9817xf7292814.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x6b44cec3x52487aa4.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x8d28fe5cx18251cfe.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x3211a425xdb9bd1d2.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fvZhmV/python-gssapi/setup.py", line 74, in <module>
        url="https://github.com/sigmaris/python-gssapi",
      File "/home/passaro/Envs/aiida-env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/passaro/Envs/aiida-env/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/home/passaro/Envs/aiida-env/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/home/passaro/Envs/aiida-env/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/home/passaro/Envs/aiida-env/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/home/passaro/Envs/aiida-env/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "/home/passaro/Envs/aiida-env/local/lib/python2.7/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/home/passaro/Envs/aiida-env/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 34, in finalize_options
        orig.build_py.finalize_options(self)
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options
        ('force', 'force'))
      File "/usr/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-install-fvZhmV/python-gssapi/setup.py", line 22, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "/tmp/pip-install-fvZhmV/python-gssapi/setup.py", line 15, in get_ext_modules
        from gssapi.bindings import ffi
      File "gssapi/__init__.py", line 4, in <module>
        from . import bindings
      File "gssapi/bindings/__init__.py", line 233, in <module>
        C = ffi.verify(_source, **_kwargs)
      File "/tmp/pip-install-fvZhmV/python-gssapi/.eggs/cffi-1.11.5-py2.7-linux-x86_64.egg/cffi/api.py", line 451, in verify
        lib = self.verifier.load_library()
      File "/tmp/pip-install-fvZhmV/python-gssapi/.eggs/cffi-1.11.5-py2.7-linux-x86_64.egg/cffi/verifier.py", line 104, in load_library
        self._compile_module()
      File "/tmp/pip-install-fvZhmV/python-gssapi/.eggs/cffi-1.11.5-py2.7-linux-x86_64.egg/cffi/verifier.py", line 201, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/tmp/pip-install-fvZhmV/python-gssapi/.eggs/cffi-1.11.5-py2.7-linux-x86_64.egg/cffi/ffiplatform.py", line 22, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "/tmp/pip-install-fvZhmV/python-gssapi/.eggs/cffi-1.11.5-py2.7-linux-x86_64.egg/cffi/ffiplatform.py", line 58, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

The error is raised when installing `python-gssapi`.
I was able to complete the installation after installing `libkrb5-dev`:
`sudo apt-get install libkrb5-dev`

**Comment by asle85** [comment]
already documented
