### ISSUE TITLE
Random "generator already executing" error in workchain tests

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2318]
Error shows up on travis on my fork:
https://travis-ci.org/ltalirz/aiida_core/jobs/464853118#L2998

Same branch passed tests on travis when run in the PR
https://travis-ci.org/aiidateam/aiida_core/builds/464853230?utm_source=github_status&utm_medium=notification

**Comment by sphuber** [comment]
Pasting the stack trace here in case the build gets lost:
```
12/07/2018 09:39:08 AM <32531> aiida.orm.node.process.workflow.workchain.WorkChainNode: [REPORT] [206|NestedWorkChain|on_except]: Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/plumpy/processes.py", line 990, in step
    next_state = yield self._run_task(self._state.execute)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/plumpy/processes.py", line 468, in _run_task
    tornado.stack_context.StackContext(self._process_scope), functools.partial(coro, *args, **kwargs))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/stack_context.py", line 390, in run_with_stack_context
    return func()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/stack_context.py", line 146, in __exit__
    self.exit(type, value, traceback)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/stack_context.py", line 126, in exit
    context.__exit__(type, value, traceback)
  File "/opt/python/2.7.14/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
ValueError: generator already executing
12/07/2018 09:39:08 AM <32531> tornado.application: [ERROR] Exception in callback <functools.partial object at 0x7f7e76389310>
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/stack_context.py", line 345, in wrapped
    raise_exc_info(exc)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/stack_context.py", line 357, in _handle_exception
    if tail.exit(*exc):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tornado/stack_context.py", line 126, in exit
    context.__exit__(type, value, traceback)
  File "/opt/python/2.7.14/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/plumpy/processes.py", line 451, in _process_scope
    "but another process! ({} != {})".format(self, Process.current())
AssertionError: Somehow, the process at the top of the stack is not me, but another process! (<NestedWorkChain> (ProcessState.WAITING) != <NestedWorkChain> (ProcessState.EXCEPTED))
```

**Comment by sphuber** [comment]
Haven't seen this one since this issue was first reported. Closing for now
