### ISSUE TITLE
verdi command locks itself out if profile list is empty

### ISSUE THREAD

**Issue by astamminger** [aiidateam/aiida_core#2424]
I used a fresh install of AiiDA and ran `verdi quicksetup` to setup a profile which failed in an early stage. This left me in a state where the `config.json` was already created with the following contents:
```
$ cat config.json 
{
    "CONFIG_VERSION": {
        "CURRENT": 3,
        "OLDEST_COMPATIBLE": 3
    },
    "profiles": {}
}
```
The profile list is obviously empty which makes `verdi` fail during the profile validation:
```
Traceback (most recent call last):
  File "/home/andreas/anaconda3/4.2.0/envs/aiida_develop_py36/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/andreas/anaconda3/4.2.0/envs/aiida_develop_py36/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/andreas/anaconda3/4.2.0/envs/aiida_develop_py36/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/andreas/anaconda3/4.2.0/envs/aiida_develop_py36/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/andreas/anaconda3/4.2.0/envs/aiida_develop_py36/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andreas/anaconda3/4.2.0/envs/aiida_develop_py36/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/andreas/anaconda3/4.2.0/envs/aiida_develop_py36/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/andreas/aiida_develop/aiida/cmdline/commands/cmd_verdi.py", line 47, in verdi
    profile = config.get_profile()
  File "/home/andreas/aiida_develop/aiida/manage/configuration/config.py", line 162, in get_profile
    self.validate_profile(name)
  File "/home/andreas/aiida_develop/aiida/manage/configuration/config.py", line 151, in validate_profile
    raise exceptions.ProfileConfigurationError('profile `{}` does not exist'.format(name))
aiida.common.exceptions.ProfileConfigurationError: profile `None` does not exist
```
This behavior is perfectly fine but when not captured renders the verdi command and its subcommands completely inaccesible (so you basically can't get out of that state because verdi quicksetup / setup also fail immediately)

**Comment by sphuber** [comment]
Fixed in PR #2425
