### ISSUE TITLE
`verdi process` calls can except when they are unroutable

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2443]
There is a bug somewhere that can cause a `Process` to be lost, which means the corresponding task is deleted from RabbitMQ before it is completed. The process will still show up in `verdi process list` but no one will ever continue running it because there is corresponding task. While the origin of this situation is more complicated and deserves its own issue, while this situation can crop up, the `verdi process` commands that try to reach the process should fail elegantly with a warning instead of throwing the following exception which is the current situation:
```
Traceback (most recent call last):
  File "/home/aiida/.virtualenvs/aiida_sdb/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/utils/decorators.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/utils/decorators.py", line 148, in decorated_function
    return function(*args, **kwargs)
  File "/home/aiida/code/aiida/env/sdb/aiida-core/aiida/cmdline/commands/cmd_process.py", line 191, in process_play
    future = controller.play_process(process.pk)
  File "/home/aiida/code/aiida/env/sdb/plumpy/plumpy/process_comms.py", line 338, in play_process
    return self._communicator.rpc_send(pid, PLAY_MSG)
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/kiwipy/rmq/communicator.py", line 608, in rpc_send
    future = self._send_message(partial(self._communicator.rpc_send, recipient_id, msg))
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/kiwipy/rmq/communicator.py", line 630, in _send_message
    return send_future.result()
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/home/aiida/.virtualenvs/aiida_sdb/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
kiwipy.communications.UnroutableError: 1 unroutable message(s) returned
```

**Comment by sphuber** [comment]
Fixed in PR #2445
