### ISSUE TITLE
ImportError: No module named setup_requirements

### ISSUE THREAD

**Issue by mguarrasi** [aiidateam/aiida_core#2457]
Dear All,

I'm trying to install Aiida on a Ubuntu 18.04 V.M.
I followed all the instruction contained in https://aiida-core.readthedocs.io/en/stable/installation/quick_install.html
However when I try to start the installation I obtained the following results:

pi_p install -e aiida_core
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Obtaining file:///home/ubuntu/Aiida_dev/aiida_core
  Installing build dependencies ... done
  **Getting requirements to build wheel ... error**
  Complete output from command /home/ubuntu/aiidapy/bin/python2 /home/ubuntu/aiidapy/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5ZdtKa:
  Traceback (most recent call last):
    File "/home/ubuntu/aiidapy/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/ubuntu/aiidapy/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ubuntu/aiidapy/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/home/ubuntu/aiidapy/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "/home/ubuntu/aiidapy/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "/home/ubuntu/aiidapy/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 21, in <module>
      from setup_requirements import install_requires, extras_require
  **ImportError: No module named setup_requirements**

  ----------------------------------------
Command "/home/ubuntu/aiidapy/bin/python2 /home/ubuntu/aiidapy/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5ZdtKa" failed with error code 1 in /home/ubuntu/Aiida_dev/aiida_core_

It seems that the setup_requirements.py is not seen.
Can you suggest me a possible solution?

Thank you,
Massimiliano.

**Comment by CasperWA** [comment]
Dear Massimiliano,

This is due to the newest version of `pip==19.0`, see #2414 and the references given therein.

You have two options:
Try to install the pen-ultimate version:
```bash
pip install pip==18.1
```
and then try installing AiiDA again, following the installation instructions.

or keep the most recent version of `pip`, but use the flag `--no-use-pep517`
```bash
pip install --no-use-pep517 -e aiida_core
```

Please let me know if this solves your issue.
/Casper

**Comment by mguarrasi** [comment]
Thank you.
It works. 

Cheers,
M.

**Comment by CasperWA** [comment]
Great - I close the issue.
This issue continues in its essence in #2414.
