### ISSUE TITLE
Pre-commit started failing for python 3 builds

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2542]
Probably one of the dependencies got a new release triggering the following exception:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/prospector", line 11, in <module>
    load_entry_point('prospector==1.1.5', 'console_scripts', 'prospector')()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/prospector/run.py", line 53, in execute
    for tool in self.config.get_tools(found_files):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/prospector/config/__init__.py", line 41, in get_tools
    config_result = tool.configure(self, found_files)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/prospector/tools/pylint/__init__.py", line 184, in configure
    config_messages += self._pylintrc_configure(pylintrc, linter)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/prospector/tools/pylint/__init__.py", line 102, in _pylintrc_configure
    are_plugins_loaded = linter.config_from_file(pylintrc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/prospector/tools/pylint/linter.py", line 27, in config_from_file
    self.load_plugin_modules(plugins)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pylint/lint.py", line 637, in load_plugin_modules
    module.register(self)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pylint_django/plugin.py", line 30, in register
    apply_augmentations(linter)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pylint_django/augmentations/__init__.py", line 763, in apply_augmentations
    suppress_message(linter, TypeChecker.visit_attribute, 'no-member', is_model_field_display_method)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 125, in suppress_message
    get_message_definition = msgs_store.get_message_definition
AttributeError: 'MessagesStore' object has no attribute 'get_message_definition'
```

**Comment by sphuber** [comment]
Fixed in PR #2543
