### ISSUE TITLE
basic_qos() got an unexpected keyword argument 'global_qos'

### ISSUE THREAD

**Issue by Cloudac7** [aiidateam/aiida_core#2704]
Dear all,
I used aiida_core v1.0.0b1 and built it as a docker image. But when I excuted `service rabbitmq-server start` and restart the daemon, error raised continuously from the message offed by `verdi daemon logshow`:

```
Traceback (most recent call last):
  File "/home/aiida/.local/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/aiida/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/aiida/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/aiida/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aiida/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/aiida/code/aiida_core/aiida/cmdline/utils/decorators.py", line 75, in decorated_function
    return function(*args, **kwargs)
  File "/home/aiida/code/aiida_core/aiida/cmdline/commands/cmd_run.py", line 112, in run
    exec(compile(handle.read(), scriptname, 'exec', dont_inherit=True), globals_dict)  # yapf: disable # pylint: disable=exec-used
  File "dft_diy_ase.py", line 116, in <module>
    dft_energy_calculation('/home/aiida/work/test/NaCl_mp-22862_conventional_standard.cif')
  File "dft_diy_ase.py", line 113, in dft_energy_calculation
    run(Cp2kCalculation, **inputs)
  File "/home/aiida/code/aiida_core/aiida/engine/launch.py", line 34, in run
    runner = manager.get_manager().get_runner()
  File "/home/aiida/code/aiida_core/aiida/manage/manager.py", line 209, in get_runner
    self._runner = self.create_runner()
  File "/home/aiida/code/aiida_core/aiida/manage/manager.py", line 245, in create_runner
    settings['communicator'] = self.get_communicator()
  File "/home/aiida/code/aiida_core/aiida/manage/manager.py", line 118, in get_communicator
    self._communicator = self.create_communicator()
  File "/home/aiida/code/aiida_core/aiida/manage/manager.py", line 169, in create_communicator
    testing_mode=testing_mode,
  File "/home/aiida/.local/lib/python3.6/site-packages/kiwipy/rmq/communicator.py", line 473, in connect
    communicator.start()
  File "/home/aiida/.local/lib/python3.6/site-packages/kiwipy/rmq/communicator.py", line 553, in start
    start_future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/aiida/.local/lib/python3.6/site-packages/kiwipy/rmq/communicator.py", line 535, in do_connect
    yield self._communicator.connect()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aiida/.local/lib/python3.6/site-packages/kiwipy/rmq/communicator.py", line 363, in connect
    yield self._message_subscriber.connect()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aiida/.local/lib/python3.6/site-packages/kiwipy/rmq/communicator.py", line 179, in connect
    self._channel = yield self._connection.channel()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aiida/.local/lib/python3.6/site-packages/topika/connection.py", line 240, in channel
    yield channel.initialize()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aiida/.local/lib/python3.6/site-packages/topika/robust_channel.py", line 83, in initialize
    yield self.set_qos(prefetch_count=prefetch_count, prefetch_size=prefetch_size)
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aiida/.local/lib/python3.6/site-packages/topika/robust_channel.py", line 97, in set_qos
    timeout=timeout,
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aiida/.local/lib/python3.6/site-packages/topika/common.py", line 174, in wrap
    raise gen.Return((yield func(self, *args, **kwargs)))
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/aiida/.local/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/aiida/.local/lib/python3.6/site-packages/topika/channel.py", line 355, in set_qos
    callback=f.set_result,
TypeError: basic_qos() got an unexpected keyword argument 'global_qos'
```

Also, when I tried to submit a calculation task in `verdi run`, the error above also raised.
How could I deal with it? Thanks!

**Comment by sphuber** [comment]
You have the wrong version of some libraries.
Do a `pip freeze | grep -E 'plumpy|kiwipy|pika'`
It should show the versions:
```
plumpy==0.13.1
kiwipy==0.5.0
topika==0.2.0
pika==1.0.0
```
If this is not the case, install the correct version e.g. `pip install topika==0.2.0`
After that make sure to restart the daemon and it should be good to go

**Comment by Cloudac7** [comment]
> You have the wrong version of some libraries.
> Do a `pip freeze | grep -E 'plumpy|kiwipy|pika'`
> It should show the versions:
> 
> ```
> plumpy==0.13.1
> kiwipy==0.5.0
> topika==0.2.0
> pika==1.0.0
> ```
> If this is not the case, install the correct version e.g. `pip install topika==0.2.0`
> After that make sure to restart the daemon and it should be good to go

Thanks, it works. And in the `setup.json` attached with the aiida_core v1.0.0b1 release, the libraries above are in old version, which might cause the very error when installed with pip. In fact, when I tried to install the correct version, dependency warning raised.

**Comment by sphuber** [comment]
Thanks for the report. This has already been addressed in the current `develop` and we will probably soon be releasing `1.0.0b2`
