### ISSUE TITLE
Transport task fails for an .hdf file

### ISSUE THREAD

**Issue by Tseplyaev** [aiidateam/aiida_core#2725]
1.0.0b1 version, python 2.7

When I submit a particular calculation, an `inp.xml` and `cdn_last.hdf` files need to be copied from local to remote machine via ssh. However, only the `inp.xml` is successfully transported to the remote machine while `cdf_last.hdf` is not. See the output:

```
04/08/2019 03:16:40 PM <22387> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [INFO] out folder path 13557f20-a39b-487c-bd1d-f315152c825c
04/08/2019 03:16:40 PM <22387> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [INFO] local copy file list [('2038166c-1d15-4354-b859-3673e7551271', u'inp.xml', u'inp.xml'), ('13557f20-a39b-487c-bd1d-f315152c825c', 'cdn_last.hdf', 'cdn.hdf')]
04/08/2019 03:17:11 PM <22387> aiida.engine.processes.calcjobs.tasks: [INFO] uploading calculation<24156>

###########
inp.xml
###########
cdn_last.hdf
04/08/2019 03:17:14 PM <22387> aiida.engine.transports: [ERROR] Exception whilst using transport:
Traceback (most recent call last):
  File "/Users/tsep/Documents/aiida/aiida_core/aiida/engine/transports.py", line 106, in request_transport
    yield transport_request.future
  File "/Users/tsep/Documents/aiida/aiida_core/aiida/engine/processes/calcjobs/tasks.py", line 78, in do_upload
    raise Return(execmanager.upload_calculation(node, transport, calc_info, script_filename))
  File "/Users/tsep/Documents/aiida/aiida_core/aiida/engine/daemon/execmanager.py", line 165, in upload_calculation
    handle.write(data_node.get_object_content(filename))
  File "/Users/tsep/Documents/aiida/aiida_core/aiida/orm/nodes/node.py", line 683, in get_object_content
    return self._repository.get_object_content(key)
  File "/Users/tsep/Documents/aiida/aiida_core/aiida/orm/utils/repository.py", line 137, in get_object_content
    return handle.read()
  File "/Users/tsep/aiidapy/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte

```

This part 
```
###########
inp.xml
###########
cdn_last.hdf
```
appeared because I changed `aiida_core/aiida/orm/utils/repository.py` a little bit to track the problem:
```
    def open(self, key, mode='r'):
        """Open a file handle to an object stored under the given key.

        :param key: fully qualified identifier for the object within the repository
        :param mode: the mode under which to open the handle
        """
        print('###########')
        print(key)
        return io.open(self._get_base_folder().get_abs_path(key), mode=mode)
```

Apparently aiida_core tries to open an hdf-file and fails decoding it via utf-8 which did not happen in 1.0.0a4 version. 

Calculation folder on the remote machine contains successfully transported `inp.xml` file:
```
[tseplyaev1@jrl01 0fd5-83ed-461f-92b5-56c05ffb1ca6]$ ls -al
total 20
drwxr-sr-x 3 tseplyaev1 cjias1f 4096 Apr  8 15:17 .
drwxr-sr-x 3 tseplyaev1 cjias1f 4096 Apr  8 15:17 ..
drwxr-sr-x 2 tseplyaev1 cjias1f 4096 Apr  8 15:17 .aiida
-rw-r--r-- 1 tseplyaev1 cjias1f  388 Apr  8 15:17 _aiidasubmit.sh
-rw-r--r-- 1 tseplyaev1 cjias1f 4947 Apr  8 15:17 inp.xml
```

**Comment by sphuber** [comment]
The problem is in the following lines in `aiida.engine.daemon.execmanager`:
```
with NamedTemporaryFile(mode='w+') as handle:
    handle.write(data_node.get_object_content(filename))
```
Just above it, there is the following comment
> Note, once #2579 is implemented, use the `node.open` method instead of the named temporary file in combination with the new `Transport.put_object_from_filelike`
Because this functionality does not yet exist, I *had* to read the content of the file into a stream and write it to a file, which means *guessing* the encoding. Otherwise I could just open a handle to the source file in binary mode and transfer the content as bytes. I think I might be able to redefine it and open the temporary file in binary as well.

**Comment by giovannipizzi** [comment]
@sphuber I think we should always do everything binary, even for strings, unless we *know* we are dealing with a string and we want to take care of the encoding?

**Comment by sphuber** [comment]
@giovannipizzi agreed
