### ISSUE TITLE
json.dumps fails for numpy int64, if used in python 3.6, aiida 1.0.0b2

### ISSUE THREAD

**Issue by d-tomerini** [aiidateam/aiida_core#2773]
when json.dumps is called on a int64 numpy value, an error is raised.

The use that I encountered is raised as 

 File "/aiida_core/aiida/backends/djsite/db/models.py", line 820, in create_value jsondata = json.dumps(value)
  File "/aiida_core/aiida/common/json.py", line 47, in dumps return simplejson.dumps(data, ensure_ascii=False, encoding='utf8', **kwargs)
  File "/aiida_1.0/lib/python3.6/site-packages/simplejson/__init__.py", line 399, in dumps 
    **kw).encode(obj) 
  File "/aiida_1.0/lib/python3.6/site-packages/simplejson/encoder.py", line 296, in encode     chunks = self.iterencode(o, _one_shot=True)
  File "/aiida_1.0/lib/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode     return _iterencode(o, 0)
  File "/aiida_1.0/lib/python3.6/site-packages/simplejson/encoder.py", line 273, in default     o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable

A  workaround that worked for me is an additional 'isinstance' check, and conversion to ''int' before dumping (I assume other numpy types will raise the same issue)

**Comment by borellim** [comment]
I found the same problem while running a PwBandStructureWorkChain under python 3.6.
This SO answer might help understand the reason: https://stackoverflow.com/a/50577730/3248206

Full traceback:
```
2019-05-02 12:31:47 [3854 | REPORT]:   [10942|PwBandsWorkChain|on_except]: Traceback (most recent call last):
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/backends/djsite/db/models.py", line 820, in create_value
    jsondata = json.dumps(value)
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/common/json.py", line 47, in dumps
    return simplejson.dumps(data, ensure_ascii=False, encoding='utf8', **kwargs)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/process_states.py", line 220, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/engine/processes/workchains/workchain.py", line 156, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/workchains.py", line 277, in step
    finished, result = self._child_stepper.step()
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/workchains.py", line 228, in step
    return True, self._fn(self._workchain)
  File "/home/aiidatests/repos/aiida_1.0/aiida-quantumespresso/aiida_quantumespresso/workflows/pw/bands.py", line 97, in run_seekpath
    result = seekpath_structure_analysis(self.ctx.current_structure, seekpath_parameters)
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/engine/processes/functions.py", line 145, in decorated_function
    result, _ = run_get_node(*args, **kwargs)
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/engine/processes/functions.py", line 125, in run_get_node
    result = process.execute()
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/engine/processes/functions.py", line 303, in execute
    result = super(FunctionProcess, self).execute()
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/processes.py", line 88, in func_wrapper
    return func(self, *args, **kwargs)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/processes.py", line 1060, in execute
    self.loop().run_sync(self.step_until_terminated)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/processes.py", line 1109, in step_until_terminated
    yield self.step()
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/processes.py", line 1100, in step
    self.transition_to(next_state)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/base/state_machine.py", line 326, in transition_to
    self.transition_failed(initial_state_label, label, *sys.exc_info()[1:])
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/base/state_machine.py", line 339, in transition_failed
    six.reraise(type(exception), exception, trace)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/base/state_machine.py", line 310, in transition_to
    self._enter_next_state(new_state)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/base/state_machine.py", line 374, in _enter_next_state
    self._fire_state_event(StateEventHook.ENTERED_STATE, last_state)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/base/state_machine.py", line 288, in _fire_state_event
    callback(self, hook, state)
  File "/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/plumpy/processes.py", line 308, in <lambda>
    lambda _s, _h, from_state: self.on_entered(from_state))
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/engine/processes/process.py", line 285, in on_entered
    self.update_node_state(self._state)
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/engine/processes/process.py", line 497, in update_node_state
    self.update_outputs()
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/engine/processes/process.py", line 519, in update_outputs
    output.store()
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/orm/nodes/node.py", line 1026, in store
    self._store(with_transaction=with_transaction)
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/orm/nodes/node.py", line 1057, in _store
    self._backend_entity.store(attributes, links, with_transaction=with_transaction)
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/orm/implementation/django/nodes.py", line 393, in store
    self.ATTRIBUTE_CLASS.reset_values_for_node(self.dbmodel, attributes, with_transaction=False)
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/backends/djsite/db/models.py", line 1108, in reset_values_for_node
    subspecifier_value=dbnode_node,
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/backends/djsite/db/models.py", line 796, in create_value
    subspecifier_value=subspecifier_value))
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/backends/djsite/db/models.py", line 796, in create_value
    subspecifier_value=subspecifier_value))
  File "/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/backends/djsite/db/models.py", line 822, in create_value
    raise ValueError("Unable to store the value: it must be either a basic datatype, or json-serializable: {}".format(value))
ValueError: Unable to store the value: it must be either a basic datatype, or json-serializable: -1

2019-05-02 12:31:47 [3855 | REPORT]:   [10942|PwBandsWorkChain|on_terminated]: remote folders will not be cleaned
2019-05-02 12:31:47 [3856 | REPORT]: [10926|PwBandStructureWorkChain|run_results]: bands sub-workchain failed (process state: ProcessState.EXCEPTED, exit message: None, exit status: None)
```

**Comment by borellim** [comment]
We worked around it temporarily with this patch to `aiida/backends/djsite/db/models.py`:

```patch
@@ -742,6 +742,14 @@ class DbMultipleValueAttributeBaseClass(m.Model):
             new_entry.bval = None
             new_entry.fval = None
             new_entry.dval = None
+            
+        elif isinstance(value, numpy.integer):
+            new_entry.datatype = 'int'
+            new_entry.ival = int(value)
+            new_entry.tval = ''
+            new_entry.bval = None
+            new_entry.fval = None
+            new_entry.dval = None
 
         elif isinstance(value, float):
             new_entry.datatype = 'float'
```

**Comment by ltalirz** [comment]
@sphuber does this look like a valid fix?
Given that it seems we need to deal with this ourselves, I guess this needs to go into aiida-core

https://bugs.python.org/issue24313

**Comment by sphuber** [comment]
That depends if we want to support storing numpy types directly in attributes and do any potentially necessary serialization and deserialization ourselves. Note that the current fix by @borellim will soon have to be adapted since the Django models are currently being migrated to JSONB causing these custom attribute classes to be dropped.

My question to @borellim however, is where in the `PwBandsStructureWorkChain` do we use numpy integer types?

**Comment by borellim** [comment]
I traced it back to seekpath. I added some print statements to that patch I showed above, and here is what I get:
```
cls: <class 'aiida.backends.djsite.db.models.DbAttribute'>
key: inverse_primitive_transformation_matrix.0.0
value: -1
DbNode uuid: e8e31e34-2a8e-4558-b568-a2784fa00e10
other_attribs: {}

cls: <class 'aiida.backends.djsite.db.models.DbAttribute'>
key: inverse_primitive_transformation_matrix.0.1
value: 1
DbNode uuid: e8e31e34-2a8e-4558-b568-a2784fa00e10
other_attribs: {}

(more similar ones)
```

Which I assume comes from here: https://github.com/giovannipizzi/seekpath/blob/b7845f3b46ed9d7d834de1317f103a697eed9956/seekpath/hpkot/__init__.py#L454

**Comment by ltalirz** [comment]
@giovannipizzi We discussed this during the AiiDA meeting and were a bit unsure whether we should be checking that the data put into AiiDa is serializable (which may get expensive) or whether we should leave some responsibility to the user.

What's your take on this?

**Comment by PhilippRue** [comment]
I had the very same issue in our AiiDA-KKR plugin, where in the parsers of calculations we regularly use numpy arrays and then got errors like this (in python3 only):
```
E               ValueError: Unable to store the value: it must be either a basic datatype, or json-serializable: -1
```

I currently use this fix on the aiida-core side (in `aiida/backends/djsite/db/models.py`):
```
+++ b/aiida/backends/djsite/db/models.py
@@ -697,10 +697,12 @@ class DbMultipleValueAttributeBaseClass(m.Model):
           bulk_create() call).
         """
         import datetime
+        import numpy as np
 
         from aiida.common import json
         from aiida.common.timezone import is_naive, make_aware, get_current_timezone
 
+
         if cls._subspecifier_field_name is None:
             if subspecifier_value is not None:
                 raise ValueError("You cannot specify a subspecifier value for "
@@ -735,7 +737,7 @@ class DbMultipleValueAttributeBaseClass(m.Model):
             new_entry.fval = None
             new_entry.dval = None
 
-        elif isinstance(value, six.integer_types):
+        elif isinstance(value, six.integer_types) or isinstance(value, np.integer):
             new_entry.datatype = 'int'
             new_entry.ival = value
             new_entry.tval = ''
@@ -743,7 +745,7 @@ class DbMultipleValueAttributeBaseClass(m.Model):
             new_entry.fval = None
             new_entry.dval = None
 
-        elif isinstance(value, float):
+        elif isinstance(value, float) or isinstance(value, np.floating):
             new_entry.datatype = 'float'
             new_entry.fval = value
             new_entry.tval = ''
```

Since aiida-core already has numpy as a dependency why not allow to have numpy datatypes there as well?

**Comment by sphuber** [comment]
I am not a 100% sure, because I wasn't there at the time of the original implementation, but one argument that I can imagine is that if we were to deserialize numpy datatypes to plain types, there is currently no way to serialize them again when you load them. This might be unexpected to a user who stores something as numpy integers and when loading from the database gets normal integers back. This might be a reason why we are being cautious with automatic or "hidden" deserialization. We will have to ask @giovannipizzi for the original arguments for the design
