### ISSUE TITLE
verdi setup failure

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida_core#2897]
If I try to run

```
verdi setup --non-interactive --email some.body@xyz.com --first-name Some --last-name Body --institution XYZ --db-backend django --db-username aiida --db-password aiida_db_passwd --db-name aiidadb --db-host localhost --db-port 5432 --repository /project/aiida_repository default
```
it fails with the following error:
```
Traceback (most recent call last):
  File "/home/epfl/work/venv-aiida-development/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/epfl/work/venv-aiida-development/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/epfl/work/venv-aiida-development/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/epfl/work/venv-aiida-development/lib/python3.6/site-packages/click/core.py", line 1135, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/epfl/work/venv-aiida-development/lib/python3.6/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/home/epfl/work/venv-aiida-development/lib/python3.6/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/epfl/work/venv-aiida-development/lib/python3.6/site-packages/click/core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/epfl/work/venv-aiida-development/lib/python3.6/site-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/epfl/work/aiida_core/aiida/cmdline/params/options/interactive.py", line 235, in prompt_callback
    return self.after_callback(ctx, param, value)
  File "/home/epfl/work/aiida_core/aiida/cmdline/params/options/interactive.py", line 221, in after_callback
    return self._after_callback(ctx, param, value)
  File "/home/epfl/work/aiida_core/aiida/cmdline/params/options/commands/setup.py", line 74, in get_quicksetup_repository_uri
    return get_repository_path_default(ctx)
  File "/home/epfl/work/aiida_core/aiida/cmdline/params/options/commands/setup.py", line 62, in get_repository_path_default
    if ctx.params['profile'] is None or not isinstance(ctx.params['profile'], Profile):
KeyError: 'profile'
```
I use `develop` branch, commit 1d0afd4124fb8dc93c4afe9a876357756a9bc3e6

**Comment by sphuber** [comment]
The problem has two facets:
* You are specifying the profile name `default` as an argument, but that has changed to an option `--profile`
* However, even if you do this, the exception might still raise, if you define the option towards the end. This is obviously a problem and stems from the fact that it will be parsed too late and will be required earlier. I will try and create a fix
