### ISSUE TITLE
Unable to install AiiDA

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#499]
I follow the instructions mentioned at 
http://aiida-core.readthedocs.io/en/latest/installation/index.html#optional-configuration

And I get the following error:
```
(aiidapy2)szoupanos@theospc22:/home/szoupanos/aiida/aiida_core$ pip install -e .
Obtaining file:///home/szoupanos/aiida/aiida_core
  Running setup.py (path:/home/szoupanos/aiida/aiida_core/setup.py) egg_info for package from file:///home/szoupanos/aiida/aiida_core
    fastentrypoints

    warning: no files found matching '*' under directory 'aiida/backends/tests/parser_tests/'
Downloading/unpacking pip==9.0.1 (from aiida-core==0.8.0rc2)
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking setuptools>=18.5 (from aiida-core==0.8.0rc2)
  Downloading setuptools-34.3.3-py2.py3-none-any.whl (389kB): 389kB downloaded
Downloading/unpacking wheel==0.29.0 (from aiida-core==0.8.0rc2)
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB): 66kB downloaded
Downloading/unpacking python-dateutil==2.6.0 (from aiida-core==0.8.0rc2)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB): 194kB downloaded
Downloading/unpacking python-mimeparse==0.1.4 (from aiida-core==0.8.0rc2)
  Downloading python-mimeparse-0.1.4.tar.gz
  Running setup.py (path:/home/szoupanos/aiidapy2/build/python-mimeparse/setup.py) egg_info for package python-mimeparse

Downloading/unpacking django==1.7.4 (from aiida-core==0.8.0rc2)
  Downloading Django-1.7.4-py2.py3-none-any.whl (7.4MB): 7.4MB downloaded
Downloading/unpacking django-extensions==1.5 (from aiida-core==0.8.0rc2)
  Downloading django_extensions-1.5.0-py2.py3-none-any.whl (240kB): 240kB downloaded
Downloading/unpacking tzlocal==1.3 (from aiida-core==0.8.0rc2)
  Downloading tzlocal-1.3.tar.gz
  Running setup.py (path:/home/szoupanos/aiidapy2/build/tzlocal/setup.py) egg_info for package tzlocal

Downloading/unpacking pytz==2014.10 (from aiida-core==0.8.0rc2)
  Downloading pytz-2014.10-py2.py3-none-any.whl (477kB): 477kB downloaded
Downloading/unpacking celery==3.1.25 (from aiida-core==0.8.0rc2)
  Downloading celery-3.1.25-py2.py3-none-any.whl (526kB): 526kB downloaded
Downloading/unpacking billiard==3.3.0.23 (from aiida-core==0.8.0rc2)
  Downloading billiard-3.3.0.23.tar.gz (151kB): 151kB downloaded
  Running setup.py (path:/home/szoupanos/aiidapy2/build/billiard/setup.py) egg_info for package billiard

    warning: no files found matching '*.py' under directory 'Lib'
Downloading/unpacking amqp==1.4.9 (from aiida-core==0.8.0rc2)
  Downloading amqp-1.4.9-py2.py3-none-any.whl (51kB): 51kB downloaded
Downloading/unpacking anyjson==0.3.3 (from aiida-core==0.8.0rc2)
  Downloading anyjson-0.3.3.tar.gz
  Running setup.py (path:/home/szoupanos/aiidapy2/build/anyjson/setup.py) egg_info for package anyjson

Downloading/unpacking supervisor==3.1.3 (from aiida-core==0.8.0rc2)
  Downloading supervisor-3.1.3.tar.gz (391kB): 391kB downloaded
  Running setup.py (path:/home/szoupanos/aiidapy2/build/supervisor/setup.py) egg_info for package supervisor

    warning: no previously-included files matching '*' found under directory 'docs/.build'
Downloading/unpacking meld3==1.0.0 (from aiida-core==0.8.0rc2)
  Downloading meld3-1.0.0.tar.gz
  Running setup.py (path:/home/szoupanos/aiidapy2/build/meld3/setup.py) egg_info for package meld3

Downloading/unpacking numpy==1.12.0 (from aiida-core==0.8.0rc2)
  Downloading numpy-1.12.0.zip (4.8MB): 4.8MB downloaded
  Running setup.py (path:/home/szoupanos/aiidapy2/build/numpy/setup.py) egg_info for package numpy
    Running from numpy source directory.

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking plumpy==0.7.6 (from aiida-core==0.8.0rc2)
  Downloading plumpy-0.7.6-py2-none-any.whl (45kB): 45kB downloaded
Downloading/unpacking SQLAlchemy==1.0.12 (from aiida-core==0.8.0rc2)
  Downloading SQLAlchemy-1.0.12.tar.gz (4.7MB): 4.7MB downloaded
  Running setup.py (path:/home/szoupanos/aiidapy2/build/SQLAlchemy/setup.py) egg_info for package SQLAlchemy

    warning: no files found matching '*.jpg' under directory 'doc'
    warning: no files found matching '*.mako' under directory 'doc'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'sa2to3.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Downloading/unpacking SQLAlchemy-Utils==0.31.2 (from aiida-core==0.8.0rc2)
  Downloading SQLAlchemy-Utils-0.31.2.tar.gz (109kB): 109kB downloaded
  Running setup.py (path:/home/szoupanos/aiidapy2/build/SQLAlchemy-Utils/setup.py) egg_info for package SQLAlchemy-Utils

    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files found matching 'docs/_themes/.git'
Downloading/unpacking ujson==1.35 (from aiida-core==0.8.0rc2)
  Downloading ujson-1.35.tar.gz (192kB): 192kB downloaded
  Running setup.py (path:/home/szoupanos/aiidapy2/build/ujson/setup.py) egg_info for package ujson

Downloading/unpacking enum34==1.1.2 (from aiida-core==0.8.0rc2)
  Downloading enum34-1.1.2.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/home/szoupanos/aiidapy2/build/enum34/setup.py) egg_info for package enum34

Downloading/unpacking voluptuous==0.8.11 (from aiida-core==0.8.0rc2)
  Downloading voluptuous-0.8.11.tar.gz
  Running setup.py (path:/home/szoupanos/aiidapy2/build/voluptuous/setup.py) egg_info for package voluptuous
    WARNING: Could not locate pandoc, using Markdown long_description.

Downloading/unpacking aldjemy==0.6.0 (from aiida-core==0.8.0rc2)
  Downloading aldjemy-0.6.0.tar.gz
  Running setup.py (path:/home/szoupanos/aiidapy2/build/aldjemy/setup.py) egg_info for package aldjemy

Downloading/unpacking passlib==1.7.1 (from aiida-core==0.8.0rc2)
  Downloading passlib-1.7.1-py2.py3-none-any.whl (498kB): 498kB downloaded
Downloading/unpacking validate-email==1.3 (from aiida-core==0.8.0rc2)
  Downloading validate_email-1.3.tar.gz
  Running setup.py (path:/home/szoupanos/aiidapy2/build/validate-email/setup.py) egg_info for package validate-email

Downloading/unpacking click==6.7 (from aiida-core==0.8.0rc2)
  Downloading click-6.7-py2.py3-none-any.whl (71kB): 71kB downloaded
Downloading/unpacking tabulate==0.7.5 (from aiida-core==0.8.0rc2)
  Downloading tabulate-0.7.5.tar.gz
  Running setup.py (path:/home/szoupanos/aiidapy2/build/tabulate/setup.py) egg_info for package tabulate

Downloading/unpacking ete3==3.0.0b35 (from aiida-core==0.8.0rc2)
  Downloading ete3-3.0.0b35.tar.gz (10.6MB): 10.6MB downloaded
  Running setup.py (path:/home/szoupanos/aiidapy2/build/ete3/setup.py) egg_info for package ete3

    Installing ETE (3.0.0b35)



    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '~*' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: manifest_maker: MANIFEST.in, line 17: 'global-exclude' expects <pattern1> <pattern2> ...

    warning: no previously-included files matching '*.gz' found anywhere in distribution
     - Done! -
     Warning: Optional library [numpy] could not be found
       Numpy is required for the ArrayTable and ClusterTree classes.
     Warning: Optional library [PyQt4] could not be found
       PyQt4 is required for tree visualization and image rendering.
     Warning: Optional library [lxml] could not be found
       lxml is required from Nexml and Phyloxml support.
Downloading/unpacking uritools==1.0.2 (from aiida-core==0.8.0rc2)
  Downloading uritools-1.0.2-py2.py3-none-any.whl
Downloading/unpacking psycopg2==2.7.1 (from aiida-core==0.8.0rc2)
  Downloading psycopg2-2.7.1.tar.gz (421kB): 421kB downloaded
  Running setup.py (path:/home/szoupanos/aiidapy2/build/psycopg2/setup.py) egg_info for package psycopg2

Downloading/unpacking paramiko==1.15.2 (from aiida-core==0.8.0rc2)
  Downloading paramiko-1.15.2-py2.py3-none-any.whl (165kB): 165kB downloaded
Downloading/unpacking ecdsa==0.13 (from aiida-core==0.8.0rc2)
  Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB): 86kB downloaded
Downloading/unpacking pycrypto==2.6.1 (from aiida-core==0.8.0rc2)
  Downloading pycrypto-2.6.1.tar.gz (446kB): 446kB downloaded
  Running setup.py (path:/home/szoupanos/aiidapy2/build/pycrypto/setup.py) egg_info for package pycrypto

Downloading/unpacking ipython (from aiida-core==0.8.0rc2)
  Downloading ipython-5.3.0-py2-none-any.whl (750kB): 750kB downloaded
Downloading/unpacking appdirs>=1.4.0 (from setuptools>=18.5->aiida-core==0.8.0rc2)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Downloading/unpacking six>=1.6.0 (from setuptools>=18.5->aiida-core==0.8.0rc2)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking packaging>=16.8 (from setuptools>=18.5->aiida-core==0.8.0rc2)
  Downloading packaging-16.8-py2.py3-none-any.whl
Downloading/unpacking kombu>=3.0.37,<3.1 (from celery==3.1.25->aiida-core==0.8.0rc2)
  Downloading kombu-3.0.37-py2.py3-none-any.whl (240kB): 240kB downloaded
Downloading/unpacking frozendict (from plumpy==0.7.6->aiida-core==0.8.0rc2)
  Downloading frozendict-1.2.tar.gz
  Running setup.py (path:/home/szoupanos/aiidapy2/build/frozendict/setup.py) egg_info for package frozendict

Downloading/unpacking futures (from plumpy==0.7.6->aiida-core==0.8.0rc2)
  Downloading futures-3.0.5-py2-none-any.whl
Downloading/unpacking ipaddress>=1.0.6 (from uritools==1.0.2->aiida-core==0.8.0rc2)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Downloading/unpacking pickleshare (from ipython->aiida-core==0.8.0rc2)
  Downloading pickleshare-0.7.4-py2.py3-none-any.whl
Downloading/unpacking pathlib2 (from ipython->aiida-core==0.8.0rc2)
  Downloading pathlib2-2.2.1-py2.py3-none-any.whl
Downloading/unpacking traitlets>=4.2 (from ipython->aiida-core==0.8.0rc2)
  Downloading traitlets-4.3.2-py2.py3-none-any.whl (74kB): 74kB downloaded
Downloading/unpacking simplegeneric>0.8 (from ipython->aiida-core==0.8.0rc2)
  Downloading simplegeneric-0.8.1.zip
  Running setup.py (path:/home/szoupanos/aiidapy2/build/simplegeneric/setup.py) egg_info for package simplegeneric

Downloading/unpacking prompt-toolkit>=1.0.4,<2.0.0 (from ipython->aiida-core==0.8.0rc2)
  Downloading prompt_toolkit-1.0.14-py2-none-any.whl (248kB): 248kB downloaded
Downloading/unpacking pygments (from ipython->aiida-core==0.8.0rc2)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB): 841kB downloaded
Downloading/unpacking pexpect (from ipython->aiida-core==0.8.0rc2)
  Downloading pexpect-4.2.1-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking decorator (from ipython->aiida-core==0.8.0rc2)
  Downloading decorator-4.0.11-py2.py3-none-any.whl
Downloading/unpacking backports.shutil-get-terminal-size (from ipython->aiida-core==0.8.0rc2)
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Downloading/unpacking pyparsing (from packaging>=16.8->setuptools>=18.5->aiida-core==0.8.0rc2)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Downloading/unpacking scandir (from pathlib2->ipython->aiida-core==0.8.0rc2)
  Downloading scandir-1.5.tar.gz
  Running setup.py (path:/home/szoupanos/aiidapy2/build/scandir/setup.py) egg_info for package scandir

Downloading/unpacking ipython-genutils (from traitlets>=4.2->ipython->aiida-core==0.8.0rc2)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl
Downloading/unpacking wcwidth (from prompt-toolkit>=1.0.4,<2.0.0->ipython->aiida-core==0.8.0rc2)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Downloading/unpacking ptyprocess>=0.5 (from pexpect->ipython->aiida-core==0.8.0rc2)
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel, python-dateutil, python-mimeparse, django, django-extensions, tzlocal, pytz, celery, billiard, amqp, anyjson, supervisor, meld3, numpy, plumpy, SQLAlchemy, SQLAlchemy-Utils, ujson, enum34, voluptuous, aldjemy, passlib, validate-email, click, tabulate, ete3, uritools, psycopg2, paramiko, ecdsa, pycrypto, ipython, aiida-core, appdirs, six, packaging, kombu, frozendict, futures, ipaddress, pickleshare, pathlib2, traitlets, simplegeneric, prompt-toolkit, pygments, pexpect, decorator, backports.shutil-get-terminal-size, pyparsing, scandir, ipython-genutils, wcwidth, ptyprocess
  Found existing installation: pip 1.5.4
    Uninstalling pip:
      Successfully uninstalled pip
  Found existing installation: setuptools 2.2
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for python-mimeparse
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/szoupanos/aiidapy2/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command /home/szoupanos/aiidapy2/bin/python -c "import setuptools, tokenize;__file__='/home/szoupanos/aiidapy2/build/python-mimeparse/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-koiQhb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/szoupanos/aiidapy2/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/szoupanos/aiidapy2/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves

----------------------------------------
Cleaning up...
Command /home/szoupanos/aiidapy2/bin/python -c "import setuptools, tokenize;__file__='/home/szoupanos/aiidapy2/build/python-mimeparse/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-koiQhb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/szoupanos/aiidapy2/include/site/python2.7 failed with error code 1 in /home/szoupanos/aiidapy2/build/python-mimeparse
Storing debug log for failure in /home/szoupanos/.pip/pip.log
```

Any ideas?

Thanks,
Spyros

ps: I use the commit 6715e38

**Comment by DropD** [comment]
Do you still have this issue?
I can't reproduce it, which version of Ubuntu are you using?

**Comment by DropD** [comment]
It seems this issue has been resolved otherwise
