### ISSUE TITLE
AiiDA installation (mayavi dependencies)

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#539]
I try to install the full version of AiiDA using the following command:
`(aiidapy) aiida@ubuntu-aiida-vm1:~/aiida-code$ pip install -e aiida_core[atomic_tools,docs,advanced_plotting]`

and it seems that the mayavi depends on numpy but numpy is not automatically installed.

```
(aiidapy) aiida@ubuntu-aiida-vm1:~/aiida-code$ pip install -e aiida_core[atomic_tools,docs,advanced_plotting]
Obtaining file:///home/aiida/aiida-code/aiida_core
Requirement already satisfied: pip==9.0.1 in /home/aiida/aiidapy/lib/python2.7/site-packages (from aiida-core==0.9.0rc1)
Requirement already satisfied: setuptools>=18.5 in /home/aiida/aiidapy/lib/python2.7/site-packages (from aiida-core==0.9.0rc1)
Collecting wheel==0.29.0 (from aiida-core==0.9.0rc1)
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Collecting python-dateutil==2.6.0 (from aiida-core==0.9.0rc1)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting python-mimeparse==0.1.4 (from aiida-core==0.9.0rc1)
  Using cached python-mimeparse-0.1.4.tar.gz
Collecting django==1.7.4 (from aiida-core==0.9.0rc1)
  Downloading Django-1.7.4-py2.py3-none-any.whl (7.4MB)
    100% |████████████████████████████████| 7.4MB 191kB/s
Collecting django_extensions==1.5 (from aiida-core==0.9.0rc1)
  Downloading django_extensions-1.5.0-py2.py3-none-any.whl (240kB)
    100% |████████████████████████████████| 245kB 5.6MB/s
Collecting tzlocal==1.3 (from aiida-core==0.9.0rc1)
  Downloading tzlocal-1.3.tar.gz
Collecting pytz==2014.10 (from aiida-core==0.9.0rc1)
  Downloading pytz-2014.10-py2.py3-none-any.whl (477kB)
    100% |████████████████████████████████| 481kB 3.1MB/s
Requirement already satisfied: six==1.10 in /home/aiida/aiidapy/lib/python2.7/site-packages (from aiida-core==0.9.0rc1)
Collecting celery==3.1.25 (from aiida-core==0.9.0rc1)
  Downloading celery-3.1.25-py2.py3-none-any.whl (526kB)
    100% |████████████████████████████████| 532kB 2.6MB/s
Collecting billiard==3.3.0.23 (from aiida-core==0.9.0rc1)
  Downloading billiard-3.3.0.23.tar.gz (151kB)
    100% |████████████████████████████████| 153kB 4.9MB/s
Collecting amqp==1.4.9 (from aiida-core==0.9.0rc1)
  Downloading amqp-1.4.9-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 61kB 8.3MB/s
Collecting anyjson==0.3.3 (from aiida-core==0.9.0rc1)
  Downloading anyjson-0.3.3.tar.gz
Collecting supervisor==3.1.3 (from aiida-core==0.9.0rc1)
  Downloading supervisor-3.1.3.tar.gz (391kB)
    100% |████████████████████████████████| 399kB 3.4MB/s
Collecting meld3==1.0.0 (from aiida-core==0.9.0rc1)
  Downloading meld3-1.0.0.tar.gz
Collecting numpy==1.12.0 (from aiida-core==0.9.0rc1)
  Downloading numpy-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl (16.5MB)
    100% |████████████████████████████████| 16.5MB 89kB/s
Collecting plumpy==0.7.8 (from aiida-core==0.9.0rc1)
  Downloading plumpy-0.7.8-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 7.9MB/s
Collecting SQLAlchemy==1.0.12 (from aiida-core==0.9.0rc1)
  Downloading SQLAlchemy-1.0.12.tar.gz (4.7MB)
    100% |████████████████████████████████| 4.8MB 347kB/s
Collecting SQLAlchemy-Utils==0.31.2 (from aiida-core==0.9.0rc1)
  Downloading SQLAlchemy-Utils-0.31.2.tar.gz (109kB)
    100% |████████████████████████████████| 112kB 7.4MB/s
Collecting ujson==1.35 (from aiida-core==0.9.0rc1)
  Downloading ujson-1.35.tar.gz (192kB)
    100% |████████████████████████████████| 194kB 6.0MB/s
Collecting enum34==1.1.2 (from aiida-core==0.9.0rc1)
  Downloading enum34-1.1.2.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 7.1MB/s
Collecting voluptuous==0.8.11 (from aiida-core==0.9.0rc1)
  Downloading voluptuous-0.8.11.tar.gz
Collecting aldjemy==0.6.0 (from aiida-core==0.9.0rc1)
  Downloading aldjemy-0.6.0.tar.gz
Collecting passlib==1.7.1 (from aiida-core==0.9.0rc1)
  Downloading passlib-1.7.1-py2.py3-none-any.whl (498kB)
    100% |████████████████████████████████| 501kB 15kB/s
Collecting validate_email==1.3 (from aiida-core==0.9.0rc1)
  Downloading validate_email-1.3.tar.gz
Collecting click==6.7 (from aiida-core==0.9.0rc1)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 9.6kB/s
Collecting tabulate==0.7.5 (from aiida-core==0.9.0rc1)
  Downloading tabulate-0.7.5.tar.gz
Collecting ete3==3.0.0b35 (from aiida-core==0.9.0rc1)
  Downloading ete3-3.0.0b35.tar.gz (10.6MB)
    100% |████████████████████████████████| 10.6MB 135kB/s
Collecting uritools==1.0.2 (from aiida-core==0.9.0rc1)
  Downloading uritools-1.0.2-py2.py3-none-any.whl
Collecting psycopg2==2.7.1 (from aiida-core==0.9.0rc1)
  Downloading psycopg2-2.7.1-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
    100% |████████████████████████████████| 2.7MB 539kB/s
Collecting paramiko==1.15.2 (from aiida-core==0.9.0rc1)
  Downloading paramiko-1.15.2-py2.py3-none-any.whl (165kB)
    100% |████████████████████████████████| 174kB 15kB/s
Collecting ecdsa==0.13 (from aiida-core==0.9.0rc1)
  Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 12kB/s
Collecting pycrypto==2.6.1 (from aiida-core==0.9.0rc1)
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 450kB 2.8MB/s
Collecting ipython (from aiida-core==0.9.0rc1)
  Downloading ipython-5.3.0-py2-none-any.whl (750kB)
    100% |████████████████████████████████| 757kB 25kB/s
Collecting mayavi==4.5.0 (from aiida-core==0.9.0rc1)
  Downloading mayavi-4.5.0.tar.bz2 (6.9MB)
    100% |████████████████████████████████| 6.9MB 238kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3id5cr/mayavi/setup.py", line 68, in <module>
        import numpy
    ImportError: No module named numpy

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3id5cr/mayavi/
```
In the same time, numpy can be installed without any problem

```
(aiidapy) aiida@ubuntu-aiida-vm1:~/aiida-code$ pip install numpy
Collecting numpy
  Downloading numpy-1.12.1-cp27-cp27mu-manylinux1_x86_64.whl (16.5MB)
    100% |████████████████████████████████| 16.5MB 91kB/s
Installing collected packages: numpy
Successfully installed numpy-1.12.1
```

**Comment by giovannipizzi** [comment]
I would say that this is a bug of mayavi that does not depend on numpy. I would close this issue and open one on the mayavi github repo.

**Comment by greschd** [comment]
On the [mayavi PyPI page](https://pypi.python.org/pypi/mayavi), it is stated that numpy and VTK must be installed *before* installing mayavi. So while it would still be nice of them to actually add the dependency, it's not *technically* a bug. It's entirely possible that this was a conscious choice.

I'm not quite sure if there's a good way to enforce that numpy gets installed before mayavi on our side, though.

**Comment by giovannipizzi** [comment]
I will take a 'drastic' approach, removing mayavi2 from the dependencies, and raising a sensible exception in the only place where it is used.
