### ISSUE TITLE
Calculations stuck in TOSUBMIT when the computer is not configured

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#540]
I ran into this issue when doing some local testing, and forgot to configure the ``localhost`` after setting it up. Since the user isn't set up for the computer, it produces this (somewhat cryptic) error in the daemon:

    [2017-05-24 17:10:43,466: WARNING/Worker-6] Error while submitting jobs for aiidauser=aiida@localhost on computer=localhost, error type is TypeError, traceback: Traceback (most recent call last):
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/aiida/daemon/execmanager.py", line 296, in submit_jobs
    computer=computer, user=aiidauser
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/aiida/backends/djsite/queries.py", line 73, in query_jobcalculations_by_computer_user_state
    **kwargs)
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/aiida/orm/implementation/django/node.py", line 149, in query
    *args, type__startswith=superclass_string, **kwargs)
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/query.py", line 709, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1331, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1358, in _add_q
    current_negated=current_negated, connector=connector)
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    lookups, value)
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1558, in get_lookup_constraint
    lookup_class(Col(alias, target, source), val), AND)
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 82, in __init__
    self.rhs = self.get_prep_lookup()
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 646, in get_prep_lookup
    return self.get_prep_value(value)
    File "/home/greschd/.virtualenvs/aiida_0.8_test/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 915, in get_prep_value
    return int(value)
    TypeError: int() argument must be a string or a number, not 'User'

The problem seems to come from the fact that ``'user': <aiida.orm.implementation.django.user.User object at 0x7fb81c1e66d0>`` is passed to the Django query as a keyword, instead of what should probably (I'm guessing here) be the DB key.

It would be nice to either directly get an error when trying to submit a calculation to a computer which doesn't pass the tests, or have a clearer error message in the daemon log.

**Comment by giovannipizzi** [comment]
My suggestion: check if the computer is configured; if it is not, go to SUBMISSIONFAILED.

**Comment by giovannipizzi** [comment]
Fixed in #578

**Comment by greschd** [comment]
Should we add a regression test for this?

**Comment by giovannipizzi** [comment]
Yes, maybe you are right. What do you think it's best? It's still a bit hard to have tests for the daemon. But maybe we can check something simpler, e.g. if we can use a AiiDA ORM object in a django query?

**Comment by greschd** [comment]
Yeah, I think it would be enough to just test that we can query by AiiDA ORM objects.
