### ISSUE TITLE
verdi calculation logshow for WorkChains throws an exception

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#563]
For WorkChains, running `verdi calculation show` often reports that there are log messages available and suggests to view them by running `verdi calculation logshow`. However, this will always throw the exception:

```
Traceback (most recent call last):
  File "/home/seb/.virtualenvs/aiida_dev/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/seb/code/aiida/core/dev/aiida/cmdline/verdilib.py", line 1204, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/seb/code/aiida/core/dev/aiida/cmdline/verdilib.py", line 1190, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/seb/code/aiida/core/dev/aiida/cmdline/baseclass.py", line 190, in run
    function_to_call(*args[1:])
  File "/home/seb/code/aiida/core/dev/aiida/cmdline/commands/calculation.py", line 309, in calculation_logshow
    state = calc.get_state()
  File "/home/seb/code/aiida/core/dev/aiida/orm/implementation/general/calculation/__init__.py", line 217, in __getattr__
    self.__class__.__name__, name))
AttributeError: 'WorkCalculation' object has no attribute 'get_state'
```

**Comment by sphuber** [comment]
I am not sure what we want the expected behavior to be here. I think it is nice to allow `verdi calculation show` to operate on `WorkCalculation` nodes, so we shouldn't remove that. The message that there are log notifications arises due to the fact that the `WorkChain.report()` mechanism uses `DbLog`. To access these, instead of `verdi calculation logshow`, users should probably use `verdi work report`, which was designed to retrieve all logs for a particular `WorkCalculation`. As it stands, I see two potential solutions.

1. In `verdi calculation show`, we detect if the node is a `WorkCalculation` and if so, we change the notification regarding log messages to use `verdi work report` instead of `verdi calculation logshow`. We would still have to add some input validation in `verdi calculation logshow` to see if the passed node is of type `Calculation` so we don't hit the exception when calling `get_state`

2. We keep the current behavior of `verdi calculation show` and simply improve `verdi calculation logshow` to properly distinguish between plain `Calculation` and `WorkCalculation` objects and display relevant information accordingly. In this solution, we might also add to the output of `verdi calculation show` that in the case of `WorkCalculation` nodes, a user might also use `verdi work report` in parallel to `verdi calculation logshow` for more detailed information.

Thoughts?
