### ISSUE TITLE
verdi import problems (SQLA profile) - set([])  contains is an empty list

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#609]
When importing the attached import file with an SQLA profile we get the following exception. 

```
(aiidapy)aiida_test@theospc22:~/wftest$ verdi import SSSP_parameters_2.aiida
**** Importing file SSSP_parameters_2.aiida
READING DATA AND METADATA...
EXTRACTING NODE DATA...
Rolling back
Traceback (most recent call last):
  File "/home/aiida_test/aiida_core/aiida/cmdline/commands/importfile.py", line 88, in run
    import_data_sqla(filename)
  File "/home/aiida_test/aiida_core/aiida/orm/importexport.py", line 984, in import_data_sqla
    relevant_db_entries = {getattr(v[0], unique_identifier): v[0] for v in qb.all()}
  File "/home/aiida_test/aiida_core/aiida/orm/querybuilder.py", line 2338, in all
    return list(self.iterall(batch_size=batch_size))
  File "/home/aiida_test/aiida_core/aiida/orm/querybuilder.py", line 2295, in iterall
    query = self.get_query()
  File "/home/aiida_test/aiida_core/aiida/orm/querybuilder.py", line 2183, in get_query
    query = self._build()
  File "/home/aiida_test/aiida_core/aiida/orm/querybuilder.py", line 1978, in _build
    self._build_filters(alias, filter_specs)
  File "/home/aiida_test/aiida_core/aiida/orm/querybuilder.py", line 1215, in _build_filters
    in filter_operation_dict.items()
  File "/home/aiida_test/aiida_core/aiida/backends/sqlalchemy/querybuilder_sqla.py", line 278, in get_filter_expr
    '{}  contains is an empty list'.format(value)
InputValidationError: set([])  contains is an empty list

> There has been an exception during the import of file
> SSSP_parameters_2.aiida
> Do you want to continue (c) or stop (S, default)? n
```

[SSSP_parameters_2.aiida.zip](https://github.com/aiidateam/aiida_core/files/1101589/SSSP_parameters_2.aiida.zip)

**Comment by lekah** [comment]
Fixed by 1f91ae62eadf12f44aaf99085cd6784045c8044a!
