### ISSUE TITLE
Tests fail with minimal installation of AiiDA (because of missing packages)

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#618]
When running the tests with a minimal AiiDA installation, some tests fail (cif, restapi, verdi_commands) because not all the needed packages have been installed.

A better solution should be envisaged apart from the test failure or forcing the developers to install all the optional AiiDA packages. For example, if a package has not been installed the related tests could be skipped.

Examples of the failures

E.g.

`verdi -p test_sqla1 devel tests`

```
Traceback (most recent call last):
  File "/home/aiida/aiidapy/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/verdilib.py", line 1212, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/verdilib.py", line 1197, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/baseclass.py", line 190, in run
    function_to_call(*args[1:])
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/commands/devel.py", line 569, in run_tests
    db_results = run_aiida_db_tests(db_test_list)
  File "/home/aiida/aiida-code/aiida_core/aiida/backends/testbase.py", line 163, in run_aiida_db_tests
    test_suite.addTest(test_loader.loadTestsFromName(modulename))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'restapi'
```

```
Traceback (most recent call last):
  File "/home/aiida/aiidapy/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/verdilib.py", line 1212, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/verdilib.py", line 1197, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/baseclass.py", line 190, in run
    function_to_call(*args[1:])
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/commands/devel.py", line 569, in run_tests
    db_results = run_aiida_db_tests(db_test_list)
  File "/home/aiida/aiida-code/aiida_core/aiida/backends/testbase.py", line 163, in run_aiida_db_tests
    test_suite.addTest(test_loader.loadTestsFromName(modulename))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'verdi_commands'
```

```
ERROR: test_export_to_file (aiida.backends.tests.dataclasses.TestTrajectoryData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aiida/aiida-code/aiida_core/aiida/backends/tests/dataclasses.py", line 2606, in test_export_to_file
    files_created = n.export(filename, fileformat=format)
  File "/home/aiida/aiida-code/aiida_core/aiida/orm/data/__init__.py", line 226, in export
    fileformat, main_file_name=path, **kwargs)
  File "/home/aiida/aiida-code/aiida_core/aiida/orm/data/__init__.py", line 187, in _exportstring
    return func(main_file_name=main_file_name, **kwargs)
  File "/home/aiida/aiida-code/aiida_core/aiida/orm/data/array/trajectory.py", line 476, in _prepare_cif
    import CifFile
ImportError: No module named CifFile
```

**Comment by sphuber** [comment]
This is currently fixed in the `release_v0.10.0` branch which will soon also be merged into `develop`. If `aiida_core` is installed with the `[testing]` extra, then the `[REST,atomic_tools]` are now also automatically installed, which are needed for the tests.
