### ISSUE TITLE
Use `reentry_scan` in setup.py

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#632]
By adding

```python
reentry_scan=['aiida']
```

to the `setup()` call, we can ensure that everytime aiida is installed (or upgraded), all plugins will automatically be discovered and registered.

I haven't gotten round to documenting the hooks reentry provides yet, but it is simple enough (module `reentry.hooks` and exposed through distutils entry points in setup.py)

**Comment by sphuber** [comment]
I experimented a bit with this issue but I am not sure this is working.
First of all, when I add `reentry_scan=['aiida']` to the `setup.py` of `aiida-core`, I get the following exception when calling `pip install -e .`

    Complete output from command python setup.py egg_info:
    fastentrypoints
    registering entry points with reentry...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/seb/code/aiida/core/dev/setup.py", line 123, in <module>
        long_description=open(path.join(aiida_folder, 'README.rst')).read(),
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/seb/.virtualenvs/aiida_plugin/local/lib/python2.7/site-packages/setuptools/dist.py", line 339, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/seb/.virtualenvs/aiida_plugin/local/lib/python2.7/site-packages/setuptools/dist.py", line 434, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/seb/.virtualenvs/aiida_plugin/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/home/seb/.virtualenvs/aiida_plugin/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2239, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'scan'

Secondly, I am not sure I understand that adding `reentry_scan=['aiida']` would ensure the automatic discovery and registry of other plugins. Instead what I did, was add `reentry` to the setup requirements of the **plugin itself** and add `reentry_register=True` to the `setup.py`. With those changes, after having installed `aiida-core`, I can simply `pip install` the plugin and its entry points are automatically recognized by `verdi`.

**Comment by DropD** [comment]
The scan hook solves the problem of recognizing already installed plugins
automatically. I can think of a use case for that beyond plugin development
early phases: A package that stands alone but also has entry points for
optionally being used with AiiDA. Then it can not be guaranteed that
aiida_core will be installed first.

The error you are getting will have to be fixed in reentry first, before
AiiDA can use it, of course.

**Comment by ltalirz** [comment]
Is this issue already fixed?

**Comment by DropD** [comment]
Not yet and it is unlikely to happen before the coding week
