### ISSUE TITLE
update migration error message

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#830]
Please improve the error message concerning db migration that is displayed after moving to v0.10.0.  Example:

```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.5.2

Exception occurred:
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/backends/djsite/utils.py", line 176, in check_schema_version
    get_current_profile())
ConfigurationError: The code schema version is 1.0.7, but the version stored in the database (DbSetting table) is 1.0.5, stopping.
To migrate to latest version, go to aiida.backends.djsite and run:
verdi daemon stop
 python manage.py --aiida-profile=test_release migrate
The full traceback has been saved in /var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/sphinx-err-ARdgGI.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
(aiida_ltal) leopold@b126028:~/Applications/aiida_ltalirz/docs

$ verdi daemon stop
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_ltal/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/verdilib.py", line 1043, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/verdilib.py", line 1028, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/baseclass.py", line 190, in run
    function_to_call(*args[1:])
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/commands/daemon.py", line 236, in daemon_stop
    load_dbenv(process='daemon')
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/backends/utils.py", line 79, in load_dbenv
    process=process, profile=profile, *args, **kwargs)
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/backends/djsite/utils.py", line 28, in load_dbenv
    check_schema_version()
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/backends/djsite/utils.py", line 176, in check_schema_version
    get_current_profile())
aiida.common.exceptions.ConfigurationError: The code schema version is 1.0.7, but the version stored in the database (DbSetting table) is 1.0.5, stopping.
To migrate to latest version, go to aiida.backends.djsite and run:
verdi daemon stop
 python manage.py --aiida-profile=test_release migrate
```

Problems:
 * `verdi daemon stop` doesn't work
 * aiida.backends.djsite is not a path

Proposal:
```
ConfigurationError: The code schema version is 1.0.7, but the version stored in the database (DbSetting table) is 1.0.5, stopping.
To migrate to latest version, run:
python path/to/aiida/backends/djsite/manage.py  --aiida-profile=test_release migrate
```

Perhaps, the correct path to manage.py could be automatically determined (just as the aiida-profile).
I guess this is something that every aiida user will see after the update, so it's worth making these instructions as clear as possible.

**Comment by sphuber** [comment]
I have implemented your suggestion of the improved migration command and made the `manage.py` dynamic, but the problem with the daemon is more complicated and have opened a separate issue #831
