### ISSUE TITLE
IntegrityError in daemon log

### ISSUE THREAD

**Issue by nmounet** [aiidateam/aiida_core#833]
It seems the daemon gets some IntegrityError every now and then: the daemon log shows lines like

[2017-10-23 11:18:42,422: ERROR/MainProcess] Task tasks.submitter[1c501c2e-dfc6-4c92-854a-d5682a20d022] raised unexpected: IntegrityError('duplicate key value violates unique constraint "db_dbsetting_key_4cac773d062e1744_uniq"\nDETAIL:  Key (key)=(daemon|task_stop|submitter) already exists.\n',)
Traceback (most recent call last):
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/aiida/codes/AiiDA/aiida_core/aiida/daemon/tasks.py", line 66, in submitter
    set_daemon_timestamp(task_name='submitter', when='stop')
  File "/home/aiida/codes/AiiDA/aiida_core/aiida/daemon/timestamps.py", line 113, in set_daemon_timestamp
    actual_task_name
  File "/home/aiida/codes/AiiDA/aiida_core/aiida/backends/djsite/globalsettings.py", line 29, in set_global_setting
    other_attribs={"description": description})
  File "/home/aiida/codes/AiiDA/aiida_core/aiida/backends/djsite/db/models.py", line 707, in set_value
    cls.objects.bulk_create(to_store)
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/django/db/models/query.py", line 409, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/django/db/models/query.py", line 938, in _batched_insert
    using=self.db)
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/aiida/aiidapy/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "db_dbsetting_key_4cac773d062e1744_uniq"
DETAIL:  Key (key)=(daemon|task_stop|submitter) already exists.

Not sure when this appeared, but it is **not** related to PR #642.

**Comment by nmounet** [comment]
Not sure when this appeared, but it is **not** related to PR #642.
Also, it does not seem harmful (daemon still continue to run normally, and calculations get done) but it still looks weird.

**Comment by borellim** [comment]
I saw a similar error in aiida_daemon.log as long as I was using aiida 0.10:
```
[2018-02-02 19:48:57,475: INFO/Beat] Scheduler: Sending due task tasks.retriever (tasks.retriever)
[2018-02-02 19:48:57,669: INFO/MainProcess] Received task: tasks.retriever[d8ce11c8-e8ba-4dcd-8cb1-5048452cbae6]
[2018-02-02 19:48:57,670: WARNING/Worker-2] aiida.daemon.tasks.retrieve:  Checking for calculations to retrieve
[2018-02-02 19:48:57,675: INFO/MainProcess] Received task: tasks.retriever[1aa82205-3ae6-4806-8d50-0fdc44cd691e]
[2018-02-02 19:48:57,676: WARNING/Worker-4] aiida.daemon.tasks.retrieve:  Checking for calculations to retrieve
[2018-02-02 19:48:57,689: INFO/MainProcess] Task tasks.retriever[d8ce11c8-e8ba-4dcd-8cb1-5048452cbae6] succeeded in 0.0195502720308s: None
[2018-02-02 19:48:57,691: ERROR/MainProcess] Task tasks.retriever[1aa82205-3ae6-4806-8d50-0fdc44cd691e] raised unexpected: IntegrityError('duplicate key value violates unique constraint "db_dbsetting_key_4cac773d062e1744_uniq"\nDETAIL:  Key (key)=(daemon|task_stop|retriever) already exists.\n',)
Traceback (most recent call last):
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mborelli/venvs/aiida/lib/python2.7/site-packages/aiida/daemon/tasks.py", line 93, in retriever
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/aiida/daemon/timestamps.py", line 113, in set_daemon_timestamp
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/aiida/backends/djsite/globalsettings.py", line 29, in set_global_setting
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/aiida/backends/djsite/db/models.py", line 707, in set_value
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/django/db/models/query.py", line 409, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/django/db/models/query.py", line 938, in _batched_insert
    using=self.db)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "db_dbsetting_key_4cac773d062e1744_uniq"
DETAIL:  Key (key)=(daemon|task_stop|retriever) already exists.
```

Now that I switched to aiida 0.11.0, aiida_daemon.log is not updated any more. Instead I see a similar (but not identical) error in celery.log; I don't know if the two things are related:
```
02/05/2018 01:34:18 PM, aiida.execmanager: [WARNING] There was an exception for calculation 99294 (IntegrityError): duplicate key value violates unique constraint "db_dbattribute_dbnode_id_10206dc8cec3d0be_uniq"
DETAIL:  Key (dbnode_id, key)=(99294, scheduler_state) already exists.
```
