### ISSUE TITLE
Import errors during loading of workflow plugin are misleading

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#884]
I just tried to load a workflow through the plugin system which failed with the following stack trac:

```
Traceback (most recent call last):
  File "/home/sphuber/.virtualenvs/aiida_binary/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/sphuber/code/aiida/core/binary/aiida/cmdline/verdilib.py", line 1043, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/sphuber/code/aiida/core/binary/aiida/cmdline/verdilib.py", line 1028, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/sphuber/code/aiida/core/binary/aiida/cmdline/verdilib.py", line 871, in run
    exec (f, globals_dict)
  File "./tests/workflows/pw/bands.py", line 13, in <module>
    PwBandsWorkChain = WorkflowFactory('quantumespresso.pw.bands')
  File "/home/sphuber/code/aiida/core/binary/aiida/orm/utils.py", line 50, in WorkflowFactory
    return BaseFactory(module, Workflow, "aiida.workflows")
  File "/home/sphuber/code/aiida/core/binary/aiida/common/pluginloader.py", line 178, in BaseFactory
    return get_plugin(category, module)
  File "/home/sphuber/code/aiida/core/binary/aiida/common/pluginloader.py", line 122, in get_plugin
    raise LoadingPluginFailed("Loading the plugin '{}' failed".format(name))
aiida.common.exceptions.LoadingPluginFailed: Loading the plugin 'quantumespresso.pw.bands' failed
```

The real reason being that the plugin class tried to import a package that was not installed. We should see if it is possible to get the real reason for the failure of loading the plugin and displaying that, such that it is immediately clear why the loading of the plugin really failed.

**Comment by sphuber** [comment]
This was a duplicate of #1019 and was already fixed in PR #1029
