### ISSUE TITLE
Daemon Broker for SQLA

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#885]
Currently we use SQLA and the database as a broker for celery.
This is a sub-optimal (?) solution since it is not listed at the list of supported brokers
http://docs.celeryproject.org/en/latest/getting-started/brokers/

Moreover, they say that we should not use SQLA as a broker

> Experimental Status
> The SQLAlchemy transport is unstable in many areas and there are several issues open. Unfortunately we don’t have the resources or funds required to improve the situation, so we’re looking for contributors and partners willing to help.

http://docs.celeryproject.org/en/3.1/getting-started/brokers/sqlalchemy.html

During the execution of some workflows, I get the following message that I did not have time to fully investigate.

```
[2017-11-02 11:27:06,572: INFO/Beat] beat: Starting...
[2017-11-02 11:27:07,053: INFO/MainProcess] Connected to sqla+postgresql://aiida:pkiMc72LPRGfyV3y@localhost:5432/test_workflows_sqla
[2017-11-02 11:27:07,069: INFO/Beat] Scheduler: Sending due task tasks.submitter (tasks.submitter)
[2017-11-02 11:27:07,296: ERROR/Beat] Message Error: Couldn't apply scheduled task tasks.submitter: (psycopg2.IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(queue_id_sequence, 2200) already exists.
 [SQL: 'CREATE SEQUENCE queue_id_sequence']
['  File "/home/aiida_test/aiidapy/bin/celery", line 11, in <module>\n    sys.exit(main())\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/__main__.py", line 30, in main\n    main()\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main\n    cmd.execute_from_commandline(argv)\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/bin/celery.py", line 785, in handle_argv\n    return self.execute(command, argv)\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/bin/celery.py", line 717, in execute\n    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv\n    return self(*args, **options)\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run\n    state_db=self.node_format(state_db, hostname), **kwargs\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start\n    self.blueprint.start(self)\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start\n    step.start(parent)\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start\n    return self.obj.start()\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/billiard/process.py", line 137, in start\n    self._popen = Popen(self)\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/billiard/forking.py", line 105, in __init__\n    code = process_obj._bootstrap()\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/billiard/process.py", line 292, in _bootstrap\n    self.run()\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/beat.py", line 553, in run\n    self.service.start(embedded_process=True)\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/beat.py", line 479, in start\n    interval = self.scheduler.tick()\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/beat.py", line 221, in tick\n    next_time_to_run = self.maybe_due(entry, self.publisher)\n', '  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/beat.py", line 207, in maybe_due\n    exc, traceback.format_stack(), exc_info=True)\n']
Traceback (most recent call last):
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/beat.py", line 204, in maybe_due
    result = self.apply_async(entry, publisher=publisher)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/beat.py", line 260, in apply_async
    entry, exc=exc)), sys.exc_info()[2])
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/beat.py", line 252, in apply_async
    **entry.options)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
    **kwargs
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/connection.py", line 449, in _ensured
    return fun(*args, **kwargs)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/messaging.py", line 184, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/messaging.py", line 111, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/common.py", line 120, in maybe_declare
    return _maybe_declare(entity, declared, ident, channel)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/common.py", line 127, in _maybe_declare
    entity.declare()
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/entity.py", line 522, in declare
    self.queue_declare(nowait, passive=False)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/entity.py", line 548, in queue_declare
    nowait=nowait)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 446, in queue_declare
    self._new_queue(queue, **kwargs)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 80, in _new_queue
    self._get_or_create(queue)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 68, in _get_or_create
    obj = self.session.query(self.queue_cls) \
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 63, in session
    _, Session = self._open()
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 56, in _open
    metadata.create_all(engine)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3695, in create_all
    tables=tables)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1856, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1481, in _run_visitor
    **kwargs).traverse_single(element)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 730, in visit_metadata
    _is_metadata_operation=True)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 755, in visit_table
    self.traverse_single(column.default)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 785, in visit_sequence
    self.connection.execute(CreateSequence(sequence))
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/aiida_test/aiidapy/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
SchedulingError: Couldn't apply scheduled task tasks.submitter: (psycopg2.IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(queue_id_sequence, 2200) already exists.
 [SQL: 'CREATE SEQUENCE queue_id_sequence']
```

What is clear is that this message doesn't appear with RabbitMQ as a broker which is easy to install.
I also have the impression that the workflow execution is also faster.

I would say to change to RabbitMQ for SQLA. What do you also think?
The change and the installation seems easy.

**Comment by szoupanos** [comment]
Just for reference,  the broker is defined in aiida/daemon/tasks.py

**Comment by dev-zero** [comment]
If we required RabbitMQ anyway I would go for RabbitMQ as a backend. I personally used Redis since I considered it to be easier to setup, secure and maintain than RabbitMQ.
