### ISSUE TITLE
Pickles cannot be created on a different hard drive

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#981]
When the repository folder is on a separate hard drive, launching workflows does not work, and they remain in the ``RUNNING`` state forever because their pickles are not created.

**Comment by greschd** [comment]
Traceback: 
```
[2017-12-09 01:21:13,355: WARNING/Worker-2] Failed to load checkpoint '/home/alps/aiida_tbextraction/repository/workflows/running/934.pickle' (deleting)
Traceback (most recent call last):
  File "/home/greschd/tbextraction/source/aiida_core/aiida/work/persistence.py", line 166, in load_all_processes
  File "/home/greschd/tbextraction/source/aiida_core/aiida/work/persistence.py", line 198, in create_from_file_and_persist
  File "/home/greschd/tbextraction/source/aiida_core/aiida/work/persistence.py", line 375, in load_checkpoint_from_file_object
    def _save_noraise(self, process):
  File "/home/greschd/tbextraction/source/aiida_core/aiida/work/persistence.py", line 431, in _load_nodes_from
    # being abel to recover the node from this if not stored
  File "/home/greschd/tbextraction/source/aiida_core/aiida/orm/utils.py", line 176, in load_node
    qb = create_node_id_qb(**kwargs)
  File "/home/greschd/tbextraction/source/aiida_core/aiida/orm/utils.py", line 116, in create_node_id_qb
    qb = QueryBuilder()
  File "/home/greschd/tbextraction/source/aiida_core/aiida/orm/querybuilder.py", line 184, in __init__
    else:
  File "/home/greschd/tbextraction/source/aiida_core/aiida/orm/querybuilder.py", line 1094, in set_with_dbpath
    is_attribute = (
AttributeError: 'QueryBuilderImplDjango' object has no attribute 'prepare_with_dbpath'
```
