### ISSUE TITLE
`verdi export migrate` fails with large files

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida_core#998]
`verdi export migrate` fails with an error if the input file is too big:

```
$ verdi export migrate bulk_materials.aiida bulk_materials.aiida.v3
READING DATA AND METADATA...
EXTRACTING NODE DATA...
Traceback (most recent call last):
  File "/home/mborelli/venvs/aiida/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1043, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1028, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/aiida/cmdline/baseclass.py", line 190, in run
    function_to_call(*args[1:])
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/aiida/cmdline/commands/exportfile.py", line 31, in cli
    verdi()
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mborelli/venvs/aiida/local/lib/python2.7/site-packages/aiida/cmdline/commands/exportfile.py", line 213, in migrate
    archive.write(real_src, real_dest)
  File "/usr/lib/python2.7/zipfile.py", line 1148, in write
    self._writecheck(zinfo)
  File "/usr/lib/python2.7/zipfile.py", line 1114, in _writecheck
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Files count would require ZIP64 extensions
```

This was experienced with a 710 MB file. We worked around the problem by exporting the same set of nodes into three smaller export files, then converting those.

[This is the file that triggered the error](https://drive.google.com/a/epfl.ch/file/d/1NuDmPWAmNiuKMiNEvjqSuQ1wwJNE_FQD/view?usp=sharing) (only viewable within EPFL).

**Comment by giovannipizzi** [comment]
Probably it's just a matter of adding a parameter to all the calls that write zip files:
https://stackoverflow.com/questions/29830531/python-using-zip64-extensions-when-compressing-large-files

**Comment by giovannipizzi** [comment]
(or one should use .tar.gz format, it should be one of the options of verdi export, I don't know if verdi export migrate supports this)

**Comment by nmounet** [comment]
`verdi export create` supports the tar.gz option, not yet `verdi export migrate`

**Comment by nmounet** [comment]
actually, currently in the `migrate` command, the output format (zip or tar.gz) depends on the input file format.
The question is: is this mandatory?
